### ISSUE TITLE
建议增加通知错误信息查看，手动通知测试

### ISSUE THREAD

**Issue by chenqy1** [ouqiang/gocron#101]

**Comment by chenqy1** [comment]
建议支持将通知模板解析后的内容作为常量传递给URL POST请求的特定变量,，以方便调用第三方告警接口

**Comment by ouqiang** [comment]
如果需要调用第三方接口，可以在收到webhook通知后自行处理。

**Comment by Jinrenjie** [comment]
@chenqy1 我目前正在实现这方面的功能，可以关注 https://github.com/betterde/ects，
欢迎加入ECTS，群聊号码：872799101，希望一起讨论需求
