### ISSUE TITLE
使用docker，数据库连接一直失败,求docker的经验

### ISSUE THREAD

**Issue by luzihang123** [ouqiang/gocron#105]

**Comment by ouqiang** [comment]
根据你的环境配置， 比如DB是独立的容器, 在gocron安装界面 MySQL HOST填入db就可以了

docker run --name gocron -p 5920:5920  --link db:db -d ouqg/gocron

**Comment by luzihang123** [comment]
DB是独立的容器,这种情况解决了，方法如下
启动mysql
```shell
docker run --name gocron-mysql -e MYSQL_ROOT_PASSWORD=123456  -e MYSQL_DATABASE=gocron -e MYSQL_USER=clark -e MYSQL_PASSWORD=123456 -d mysql:5.6
```
启动gocron
```shell
docker run --name gocron -p 5920:5920 --link gocron-mysql:mysql -d ouqg/gocron
```
设置界面
![](https://ws1.sinaimg.cn/large/006tNbRwly1fy6a9blquij314v0u0t9b.jpg)

**Comment by luzihang123** [comment]
我想通过gocron，在宿主机定时执行shell命令。任务节点的主机名该写什么？![](https://ws4.sinaimg.cn/large/006tNbRwly1fy6bkqtdp1j30zi0tqt8v.jpg)

**Comment by zjie-zhang** [comment]
节点配置解决了吗

**Comment by luzihang123** [comment]
> 节点配置解决了吗

没用了

**Comment by luzihang123** [comment]
> 节点配置解决了吗

你还在解决这个问题吗？
