### ISSUE TITLE
建议增加 邮箱测试功能 

### ISSUE THREAD

**Issue by gaoluhua99** [ouqiang/gocron#106]
建议增加邮箱测试功能，谢谢

**Comment by astrisk** [comment]
我也是配置了邮件通知，但是无效，日志也没看到啥信息。没有测试功能，是很不方便。

**Comment by ouqiang** [comment]
@astrisk 如果邮件发送失败会记录日志

配置好邮件服务器后，可以添加一条任务测试邮件发送是否正常
