### ISSUE TITLE
-bash: ./gocron-node: cannot execute binary file

### ISSUE THREAD

**Issue by WanSeLiangWei** [ouqiang/gocron#11]
-bash: ./gocron-node: cannot execute binary file

请问下，这个是什么错误呀

**Comment by ouqiang** [comment]
你下载的是Mac可执行文件在Linux上运行？，提供一下系统信息及下载的gocron-node压缩包名称

**Comment by WanSeLiangWei** [comment]
gocron-linux-amd64.tar.gz

**Comment by WanSeLiangWei** [comment]
gocron-node-linux-amd64.tar.gz
下载的是这 2个文件

**Comment by ouqiang** [comment]
gocron-node有可执行权限吗
系统是64位置吗

**Comment by WanSeLiangWei** [comment]
嗯，系统是 Mac，
./gocron web 也是这个错误，需要转 go 语言的开发环境吗？

**Comment by ouqiang** [comment]
系统是Mac要下载darwin压缩包

**Comment by WanSeLiangWei** [comment]
uname -a
Darwin liangweideMBP.lan 15.6.0 Darwin Kernel Version 15.6.0: Fri Feb 17 10:21:18 PST 2017; root:xnu-3248.60.11.4.1~1/RELEASE_X86_64 x86_64

**Comment by WanSeLiangWei** [comment]
好的，谢谢，我再试试

**Comment by WanSeLiangWei** [comment]
用darwin包安装好了，想了解下，添加任务里面，执行方式为 shell，如何链接到我的服务器，再执行某个命令，要写链接到服务器的 shell 命令吗？ 比如 ：ssh web@192.168.1.1，

**Comment by WanSeLiangWei** [comment]
用darwin包安装好了，想了解下，添加任务里面，执行方式为 shell，如何链接到我的服务器，再执行某个命令，要写链接到服务器的 shell 命令吗？ 比如 ：
ssh web@192.168.1.1
cat /var/log/cron.log

是这么写吗？

**Comment by WanSeLiangWei** [comment]
哦，明白了，是运行 ./gocron-node，然后添加到节点，然后写 shell 脚本
