### ISSUE TITLE
packets.go:130: write tcp 127.0.0.1:47730->127.0.0.1:3306: write: broken pipe

### ISSUE THREAD

**Issue by gdlwolf** [ouqiang/gocron#110]
日志中每天都可以看到类似如下这样的信息：
[mysql] 2019/01/04 13:47:57 packets.go:130: write tcp 127.0.0.1:47730->127.0.0.1:3306: write: broken pipe
[mysql] 2019/01/04 13:47:57 packets.go:130: write tcp 127.0.0.1:47730->127.0.0.1:3306: write: broken pipe
[mysql] 2019/01/04 13:47:57 packets.go:130: write tcp 127.0.0.1:47732->127.0.0.1:3306: write: broken pipe
[mysql] 2019/01/04 13:47:57 packets.go:130: write tcp 127.0.0.1:47732->127.0.0.1:3306: write: broken pipe

请问这是哪里出了问题？

**Comment by gdlwolf** [comment]
您好，
我的数据库是Percona mysql 5.6.42,wait_timeout值是28800，即8小时，如果程序每3分钟ping一次mysql来保活的话，那是不是不应该出现这样的报错：broken pipe

**Comment by ouqiang** [comment]
可能是其他原因导致连接断开了

**Comment by ouqiang** [comment]
v1.5.1已设置连接最大存活时间为2小时
