### ISSUE TITLE
引用tsx的模板时，无法渲染

### ISSUE THREAD

**Issue by Yves-yuan** [ouqiang/gocron#112]
在项目中引用使用tsx的组件时，无法渲染。
`import VueLoading from './components/common/Loading.vue'
<vue-loading type="bars" color="#d9544e" :size="{ width: '50px', height: '50px' }"></vue-loading>`
想在项目中使用一个loading图标的模板，通过yarn安装了该模板引入后不能渲染成功。

**Comment by ouqiang** [comment]
这个你需要自己排查，前端我不擅长
