### ISSUE TITLE
windows 下 make package-all 打包失败

### ISSUE THREAD

**Issue by Yves-yuan** [ouqiang/gocron#113]
windows 环境下尝试打包，使用make package-all命令，结果报错：
`./package.sh: line 2: $'\r': command not found
./package.sh: line 5: $'\r': command not found
: invalid option name set: errexit
: invalid option name set: nounset
: invalid option name: set: pipefail
./package.sh: line 12: $'\r': command not found
./package.sh: line 14: $'\r': command not found
./package.sh: line 19: $'\r': command not found
./package.sh: line 24: $'\r': command not found
./package.sh: line 37: $'\r': command not found
./package.sh: line 46: $'\r': command not found
./package.sh: line 48: syntax error near unexpected token `$'{\r''
'/package.sh: line 48: `git_latest_tag() {`

**Comment by ouqiang** [comment]
这个只能用于Unix环境，不支持Windows哦

**Comment by Yves-yuan** [comment]
流泪。在centos下make package 还是报上面那个错。。

**Comment by ouqiang** [comment]
$'\r': command not found  

需要把windows的换行符\r去掉
