### ISSUE TITLE
本地数据库连接失败，表单无法提交

### ISSUE THREAD

**Issue by KaraBilly** [ouqiang/gocron#118]
数据库配置时候总是连接数据库失败，但无法看到具体错误，望帮助，谢谢

**Comment by ouqiang** [comment]
连不上数据库就是具体错误了，数据库IP端口配置是对的吗

**Comment by KaraBilly** [comment]
使用云上的数据库就可以了，估计是认证的问题

**Comment by mringg** [comment]
这块没把具体的错误信息吐出来，可以检查下地址/端口/用户名/密码/数据库名是否对 @KaraBilly
