### ISSUE TITLE
gocron

### ISSUE THREAD

**Issue by lixiaohong0212** [ouqiang/gocron#12]
账户计划做权限吗？分为只读和可操作就可以了

**Comment by ouqiang** [comment]
整个后台做权限控制, 还是只针对任务模块, 能详细说一下吗？

**Comment by jagerzhang** [comment]
个人也是建议后续能将权限控制做的更细化，比如多个账号，区分管理和只读账号，如果任务还能分类，就更好了。

**Comment by jagerzhang** [comment]
不知道能否加个QQ交流交流~~ 287988783
