### ISSUE TITLE
重新安装的问题

### ISSUE THREAD

**Issue by liuhhua008** [ouqiang/gocron#120]
MYSQL数据库还在，重新部署应用的话，还是要强行安装。并且要重新建表。提示我说表已存在，报错。不让进。非得把原来的表都删除吗？原来里面的任务不都白瞎了吗？这不科学吧？

**Comment by ouqiang** [comment]
不支持重新安装哈

**Comment by GreenHatHG** [comment]
我是用docker，找到conf的文件夹，然后映射为之前的conf文件夹
