### ISSUE TITLE
windows shell命令被转码

### ISSUE THREAD

**Issue by liuhhua008** [ouqiang/gocron#121]
cmd /c for /f "tokens=1,3 delims= " %j in ('query user') do (logoff %k)
start c:\123.rdp
主机: [2003虚拟机-192.168.157.129:5921]
exit status 1
此时不应有 \"tokens=1,3 delims= \"。
 在这里 ” 被自动 转成了 \"  多了个\  怎么回事？

**Comment by liuhhua008** [comment]
echo "
主机: [2003虚拟机-192.168.157.129:5921]

\"

**Comment by liuhhua008** [comment]
GIT hub 把 "\ 又强行 变成了 ” 问题都没法反映 哎~~~

**Comment by ouqiang** [comment]
windows命令行我不太熟，试试把命令写到文件中，调用bat执行

**Comment by liuhhua008** [comment]
看来只能那么搞了，其它我看一切都正常 就是 “ 会被转成 \"
