### ISSUE TITLE
linux shell执行问题

### ISSUE THREAD

**Issue by wgngoo** [ouqiang/gocron#123]
作者你好，
      最近在研究你编写的gocron源码，学习一下实现思想，有个问题请教你，问题如下：

func ExecShell(ctx context.Context, command string) (string, error) {
	cmd := exec.Command("/bin/bash", "-c", command)
	cmd.SysProcAttr = &syscall.SysProcAttr{
		Setpgid : true,
	}
	resultChan := make(chan Result)
	go func() {
		output, err := cmd.CombinedOutput()
		resultChan <- Result{string(output), err}

	}()
	select {
	case <-ctx.Done():
		if cmd.Process.Pid > 0 {
			syscall.Kill(-cmd.Process.Pid, syscall.SIGKILL)
		}
		return "", errors.New("timeout killed")
	case result := <-resultChan:
		return result.output, result.err
	}

}

1、Setpgid : true
2、syscall.Kill(-cmd.Process.Pid, syscall.SIGKILL)
这两个地方在我本地调用时显示没有字段和方法，请问原因在哪里？

**Comment by ouqiang** [comment]
windows下是没有这些字段的

**Comment by wgngoo** [comment]
要在linux系统上进行开发？

**Comment by ouqiang** [comment]
我是在Mac上开发的

**Comment by wgngoo** [comment]
OK，谢谢指点
