### ISSUE TITLE
shell命令不支持管道

### ISSUE THREAD

**Issue by omyhub** [ouqiang/gocron#124]
number="ps -ef | grep proname"

类似这种，要控制进程数，shell中有管道会提示 “表单验证失败”
或者有好的办法控制进程数，每分钟跑一次，最多允许5个进程，如果已经有5个进程，就不会再启动新的进程了

**Comment by ouqiang** [comment]
shell是支持管道的，看下其他参数是否正确。

**Comment by ouqiang** [comment]
有复杂的需求写到脚本中

**Comment by ZYallers** [comment]
`#!/bin/bash
num=`ps aux | grep runBrmSynQueue | wc -l | grep -v grep`
if [ $num -lt 5 ];then
php=/apps/svr/php/bin/php
ini=/apps/conf/php/php.ini
index=/apps/data/work/php/im.hxsapp.com/index.php
source /apps/sh/env.sh
source /apps/sh/.server_env.sh
$php -c $ini -f $index api/Brm runBrmSynQueue
fi`

例如这样对shell就添加不了，老是提示验证失败。
然后我一行一行排除法之后，发现因为ps那行命令不行，加了那行命令就通过不了。

**Comment by ZYallers** [comment]
> 有复杂的需求写到脚本中

写在脚本里也是可行，但有两个不好：一是没次上线定时任务都要先找运维同事帮忙先在服务器节点里加脚本，二是每个节点都要加，这样太浪费时间，不够智能。

**Comment by ouqiang** [comment]
shell 命令长度不能超过250

**Comment by ZYallers** [comment]
> shell 命令长度不能超过250

shell命令长度能不能改长一点。555～

**Comment by ouqiang** [comment]
250个字符已经足够长了，复杂操作写到脚本中。
