### ISSUE TITLE
api签名的部分有些问题

### ISSUE THREAD

**Issue by mringg** [ouqiang/gocron#135]
问题：
ctx.Req.URL.Path会忽略掉路径的前缀 "/api"，计算签名不一致
例如：
实际请求path为：/api/v1/tasklog/remove/1
服务端中计算签名使用ctx.Req.URL.Path：/v1/tasklog/remove/1
客户端在计算签名使用的是"/api/v1/tasklog/remove/1"导致计算签名和系统不一致

**Comment by zarte** [comment]
你客户端生成签名去掉/api不就可以了

**Comment by mringg** [comment]
> 你客户端生成签名去掉/api不就可以了

文档的示例代码如下：
$apiKey = "absddd"
$time = "1495519926"
$urlPath = "/api/v1/tasklog/update-status"
$apiSecret = "lisixasdse" 
$sign = md5($apiKey . $time . $urlPath . $apiSecret)


我只是把疑问抛出来，怎么解决随意了

**Comment by kbigbus** [comment]
感谢老铁 @mringg

**Comment by Zd036** [comment]
感谢 @mringg 
一直没找到问题，现在终于解决了，多谢

**Comment by ming2050** [comment]
看来这个项目不维护了，一直打开的issue看着不舒服，就先关闭了
