### ISSUE TITLE
节点连接问题

### ISSUE THREAD

**Issue by android-coco** [ouqiang/gocron#138]
1，环境
ouqg/gocron docker 安装 在香港的一台机器
gocron-node 有4台  3台香港 1台深圳

2，问题
香港的节点没有问题
深圳的节点测试连接 失败  在安装的机器上是可以ping xxx   telnet xxx 5921 （内外网IP都可以）
啥原因了

**Comment by ouqiang** [comment]
是在gocron服务器上执行的吗
> 深圳的节点测试连接 失败 在安装的机器上是可以ping xxx telnet xxx 5921 （内外网IP都可以）

**Comment by android-coco** [comment]
是啊，比较奇怪 理论上应该可以连接才对
