### ISSUE TITLE
gocron是否支持非root账号的定时任务？

### ISSUE THREAD

**Issue by jagerzhang** [ouqiang/gocron#14]
看了一大圈任务调度，发现大神这个最轻量，很是喜欢。
刚安装了下，发现在添加节点的时候，发现没有可以填写用户的功能。
我们生产环境有很多是非root跑的业务，比如publish跑的程序， 我们的任务计划都是加到publish账号下。

不知道gocron是否能支持非root账号执行任务？我是这样想的：
如果一个服务器需要普通账号定时任务，那么就用普通账号身份去启动gocron-node？？
不过有的服务器既有root任务，又有普通账号任务，可能实现起来比较啰嗦。。
不知道后续gocron是否能支持指定账号身份，比如我都用root身份运行node，但是我可以指定这个node1以其他身份执行即可，期待大神的回复~~

**Comment by ouqiang** [comment]
1. 如果一个服务器需要普通账号定时任务，那么就用普通账号身份去启动gocron-node？？
用账号A启动gocron-node,  运行任务也是账号A

2. 有的服务器既有root任务，又有普通账号任务
用root用户启动gocron-node
以其他用户身份运行任务 runuser - user -c command

**Comment by jagerzhang** [comment]
get 到了，多谢解答。
另外咨询下，goron和gocron-node之间的通信是私有协议鉴权吗？node的安全性是否有较好的保障？

**Comment by ouqiang** [comment]
gocron和gocron-node通过RPC通信, 目前没有做鉴权, 所以不能对外暴露，后期会加入token鉴权。

**Comment by jagerzhang** [comment]
好的，期待后续的改进。

**Comment by jagerzhang** [comment]
赞！
https主要是解决数据被抓包分析的问题。我还担心另一个问题，就是其他人如果知道主机和客户端的通信协议，是不是可以其他任务？因为没有鉴权

**Comment by ouqiang** [comment]
需要拿到证书(公钥)才能和gocron-node通信,  只要公钥没泄露,  gocron-node就是安全的, [安全](https://github.com/ouqiang/gocron/wiki/安全)
