### ISSUE TITLE
ubuntu 16.04编译出错，建议弄个群

### ISSUE THREAD

**Issue by luowei729** [ouqiang/gocron#144]
internal/modules/logger/logger.go:9:2: cannot find package "gopkg.in/macaron.v1" in any of:
        /usr/local/go/src/gopkg.in/macaron.v1 (from $GOROOT)
        /root/go/src/gopkg.in/macaron.v1 (from $GOPATH)
makefile:23: recipe for target 'gocron' failed
make: *** [gocron] Error 1
root@Cloud:~/go/src/github.com/ouqiang/gocron#

**Comment by ouqiang** [comment]
需要开启go module编译
