### ISSUE TITLE
新源码编译路径错误无法编码，麻烦作者修正一下

### ISSUE THREAD

**Issue by luowei729** [ouqiang/gocron#145]
这里无法打开了导致编译错误

vim  gocron/cmd/gocron.go

// Command gocron
//go:generate statik -src=../../web/public -dest=../../internal -f

package main

import (
        "os"
        "os/signal"
        "syscall"

        "github.com/ouqiang/gocron/internal/models"
        "github.com/ouqiang/gocron/internal/modules/app"
        "github.com/ouqiang/gocron/internal/modules/logger"
        "github.com/ouqiang/gocron/internal/modules/setting"
        "github.com/ouqiang/gocron/internal/routers"
        "github.com/ouqiang/gocron/internal/service"
        "github.com/ouqiang/goutil"
        "github.com/urfave/cli"
        "gopkg.in/macaron.v1"
)

**Comment by ouqiang** [comment]
代码是没有问题的哈，需要go 1.11+，开启go module才能编译
[gocron编译](https://asciinema.org/a/WzGSJ3cFlIfKjeUiWyzJIRao5)

**Comment by luowei729** [comment]
root@iZj6ceq3yznzhcwqdnlwoaZ:~/go/pkg/mod/github.com/ouqiang/gocron@v1.5.1# make
go build  -o bin/gocron ./cmd/gocron
# runtime
/usr/local/go/src/runtime/map.go:65:2: bucketCntBits redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:64:18
/usr/local/go/src/runtime/map.go:66:2: bucketCnt redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:65:23
/usr/local/go/src/runtime/map.go:77:2: maxKeySize redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:74:17
/usr/local/go/src/runtime/map.go:78:2: maxValueSize redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:75:17
/usr/local/go/src/runtime/map.go:83:2: dataOffset redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:83:4
/usr/local/go/src/runtime/map.go:94:2: evacuatedX redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:91:19
/usr/local/go/src/runtime/map.go:95:2: evacuatedY redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:92:19
/usr/local/go/src/runtime/map.go:96:2: evacuatedEmpty redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:90:19






/usr/local/go/src/runtime/map.go:97:2: minTopHash redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:93:19
/usr/local/go/src/runtime/map.go:100:2: iterator redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:96:17
/usr/local/go/src/runtime/map.go:100:2: too many errors
# crypto/rc4
/usr/local/go/src/crypto/rc4/rc4_asm.go:13:18: (*Cipher).XORKeyStream redeclared in this block
        previous declaration at /usr/local/go/src/crypto/rc4/rc4.go:61:6
makefile:23: recipe for target 'gocron' failed
make: *** [gocron] Error 2
root@iZj6ceq3yznzhcwqdnlwoaZ:~/go/pkg/mod/github.com/ouqiang/gocron@v1.5.1#

**Comment by luowei729** [comment]
不行，依旧报错

root@iZj6ceq3yznzhcwqdnlwoaZ:~/go/pkg/mod/github.com/ouqiang/gocron@v1.5.1# make
go build  -o bin/gocron ./cmd/gocron
# runtime
/usr/local/go/src/runtime/map.go:65:2: bucketCntBits redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:64:18
/usr/local/go/src/runtime/map.go:66:2: bucketCnt redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:65:23
/usr/local/go/src/runtime/map.go:77:2: maxKeySize redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:74:17
/usr/local/go/src/runtime/map.go:78:2: maxValueSize redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:75:17
/usr/local/go/src/runtime/map.go:83:2: dataOffset redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:83:4
/usr/local/go/src/runtime/map.go:94:2: evacuatedX redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:91:19
/usr/local/go/src/runtime/map.go:95:2: evacuatedY redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:92:19
/usr/local/go/src/runtime/map.go:96:2: evacuatedEmpty redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:90:19
/usr/local/go/src/runtime/map.go:97:2: minTopHash redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:93:19
/usr/local/go/src/runtime/map.go:100:2: iterator redeclared in this block
        previous declaration at /usr/local/go/src/runtime/hashmap.go:96:17
/usr/local/go/src/runtime/map.go:100:2: too many errors
# crypto/rc4
/usr/local/go/src/crypto/rc4/rc4_asm.go:13:18: (*Cipher).XORKeyStream redeclared in this block
        previous declaration at /usr/local/go/src/crypto/rc4/rc4.go:61:6
makefile:23: recipe for target 'gocron' failed
make: *** [gocron] Error 2
root@iZj6ceq3yznzhcwqdnlwoaZ:~/go/pkg/mod/github.com/ouqiang/gocron@v1.5.1#

**Comment by luowei729** [comment]
不行，还是报错

root@iZj6chhgw5xb6zl7ohkzgrZ:~/go/src/github.com/ouqiang/gocron# make
go build  -o bin/gocron ./cmd/gocron
go: finding github.com/go-macaron/inject v0.0.0-20160627170012-d8a0b8677191
go: finding github.com/klauspost/compress v1.5.0
go: finding github.com/go-macaron/gzip v0.0.0-20160222043647-cad1c6580a07
go: finding github.com/go-xorm/builder v0.3.4
go: finding github.com/ouqiang/goutil v1.1.1
go: finding github.com/Tang-RoseChild/mahonia v0.0.0-20131226213531-0eef680515cc
go: finding github.com/go-xorm/xorm v0.7.1
go: finding google.golang.org/grpc v1.21.0
go: finding gopkg.in/gomail.v2 v2.0.0-20160411212932-81ebce5c23df
go: finding gopkg.in/ini.v1 v1.42.0
go: finding github.com/go-xorm/core v0.6.2
go: finding golang.org/x/sync v0.0.0-20181108010431-42b317875d0f
go: finding github.com/urfave/cli v1.20.0
go: finding github.com/Unknwon/com v0.0.0-20190321035513-0fed4efef755
go: finding github.com/jakecoffman/cron v0.0.0-20190106200828-7e2009c226a5
go: finding github.com/shopspring/decimal v0.0.0-20180709203117-cd690d0c9e24
go: finding github.com/jackc/fake v0.0.0-20150926172116-812a484cc733
go: finding github.com/mattn/go-sqlite3 v1.9.0
go: finding github.com/ziutek/mymysql v1.5.4
go: finding golang.org/x/sync v0.0.0-20180314180146-1d60e4601c6f
go: finding github.com/client9/misspell v0.3.4
go: finding github.com/go-macaron/toolbox v0.0.0-20180818072302-a77f45a7ce90
go: finding github.com/kr/pretty v0.1.0
go: finding github.com/smartystreets/goconvey v0.0.0-20181108003508-044398e4856c
go: finding gopkg.in/macaron.v1 v1.3.2
go: finding google.golang.org/appengine v1.1.0
go: finding github.com/davecgh/go-spew v1.1.1
go: finding github.com/stretchr/testify v1.3.0
go: finding golang.org/x/oauth2 v0.0.0-20180821212333-d2e6202438be
go: finding github.com/satori/go.uuid v1.2.0
go: finding github.com/kr/text v0.1.0
go: finding gopkg.in/alexcesaro/quotedprintable.v3 v3.0.0-20150716171945-2caba252f4dc
go: finding github.com/go-xorm/builder v0.3.2
go: finding golang.org/x/lint v0.0.0-20190313153728-d0100b6bd8b3
go: finding github.com/jtolds/gls v4.2.1+incompatible
go: finding github.com/denisenkom/go-mssqldb v0.0.0-20181014144952-4e0d7dc8888f
go: finding github.com/go-xorm/core v0.6.0
go: finding github.com/jackc/pgx v3.2.0+incompatible
go: finding google.golang.org/genproto v0.0.0-20190530194941-fb225487d101
go: finding google.golang.org/genproto v0.0.0-20180817151627-c66870c02cf8
go: finding github.com/sirupsen/logrus v1.4.2
go: finding github.com/davecgh/go-spew v1.1.0
go: finding github.com/pkg/errors v0.8.0
go: finding github.com/kr/pty v1.1.1
go: finding github.com/go-sql-driver/mysql v1.4.0
go: finding github.com/klauspost/cpuid v1.2.1
go: finding github.com/stretchr/testify v1.2.2
go: finding github.com/pmezard/go-difflib v1.0.0
go: finding google.golang.org/appengine v1.4.0
go: finding github.com/go-sql-driver/mysql v1.4.1
go: finding github.com/smartystreets/assertions v0.0.0-20190116191733-b6c0e53d7304
go: finding cloud.google.com/go v0.26.0
go: finding golang.org/x/sys v0.0.0-20190422165155-953cdadca894
go: finding github.com/lib/pq v1.1.1
go: finding gopkg.in/check.v1 v1.0.0-20180628173108-788fd7840127
go: finding github.com/stretchr/objx v0.1.0
go: finding github.com/golang/glog v0.0.0-20160126235308-23def4e6c14b
go: finding golang.org/x/text v0.3.0
go: finding github.com/golang/protobuf v1.2.0
go: finding github.com/BurntSushi/toml v0.3.1
go: finding github.com/gopherjs/gopherjs v0.0.0-20181103185306-d547d1d9531e
go: finding golang.org/x/net v0.0.0-20190522155817-f3200d17e092
go: finding github.com/cihub/seelog v0.0.0-20170130134532-f561c5e57575
go: finding github.com/google/go-cmp v0.2.0
go: finding gopkg.in/stretchr/testify.v1 v1.2.2
go: finding golang.org/x/tools v0.0.0-20190311212946-11955173bddd
go: finding golang.org/x/tools v0.0.0-20190226205152-f727befe758c
go: finding github.com/go-macaron/binding v0.0.0-20170611065819-ac54ee249c27
go: finding github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: finding github.com/rakyll/statik v0.1.6
go: finding honnef.co/go/tools v0.0.0-20190102054323-c2f93a96b099
go: finding golang.org/x/lint v0.0.0-20190227174305-5b3e6a55c961
go: finding github.com/mattn/go-sqlite3 v1.10.0
go: finding github.com/golang/mock v1.1.1
go: finding google.golang.org/grpc v1.19.0
go: finding github.com/konsorten/go-windows-terminal-sequences v1.0.1
go: finding golang.org/x/net v0.0.0-20190213061140-3a22650c66bd
go: finding github.com/go-xorm/sqlfiddle v0.0.0-20180821085327-62ce714f951a
go: finding github.com/lib/pq v1.0.0
go: finding github.com/cockroachdb/apd v1.1.0
go: finding golang.org/x/exp v0.0.0-20190121172915-509febef88a4
go: finding github.com/golang/protobuf v1.3.1
go: finding golang.org/x/net v0.0.0-20180724234803-3673e40ba225
go: finding golang.org/x/sys v0.0.0-20190215142949-d0b11bdaac8a
go: finding github.com/stretchr/objx v0.1.1
go: finding golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2
go: finding golang.org/x/crypto v0.0.0-20190530122614-20be4c3c3ed5
go: finding golang.org/x/net v0.0.0-20190311183353-d8887717615a
go: finding github.com/go-gomail/gomail v0.0.0-20160411212932-81ebce5c23df
go: finding golang.org/x/sys v0.0.0-20180830151530-49385e6e1522
go: finding golang.org/x/text v0.3.2
go: finding golang.org/x/lint v0.0.0-20181026193005-c67002cb31c3
go: finding golang.org/x/net v0.0.0-20180826012351-8a410e7b638d
go: finding golang.org/x/tools v0.0.0-20190114222345-bf090417da8b
go: finding golang.org/x/tools v0.0.0-20180917221912-90fa682c2a6e
go: finding golang.org/x/net v0.0.0-20190404232315-eb5bcb51f2a3
go: finding golang.org/x/sys v0.0.0-20190412213103-97732733099d
go: downloading github.com/cihub/seelog v0.0.0-20170130134532-f561c5e57575
go: downloading github.com/go-xorm/xorm v0.7.1
go: downloading github.com/urfave/cli v1.20.0
go: downloading github.com/go-sql-driver/mysql v1.4.1
go: downloading golang.org/x/net v0.0.0-20190522155817-f3200d17e092
go: downloading github.com/ouqiang/goutil v1.1.1
go: downloading github.com/lib/pq v1.1.1
go: downloading gopkg.in/ini.v1 v1.42.0
go: downloading gopkg.in/macaron.v1 v1.3.2
go: downloading github.com/Tang-RoseChild/mahonia v0.0.0-20131226213531-0eef680515cc
go: downloading github.com/go-macaron/binding v0.0.0-20170611065819-ac54ee249c27
go: downloading github.com/go-xorm/core v0.6.2
go: downloading google.golang.org/grpc v1.21.0
go: downloading github.com/go-macaron/toolbox v0.0.0-20180818072302-a77f45a7ce90
go: downloading golang.org/x/crypto v0.0.0-20190530122614-20be4c3c3ed5
go: downloading github.com/go-macaron/inject v0.0.0-20160627170012-d8a0b8677191
go: downloading github.com/go-macaron/gzip v0.0.0-20160222043647-cad1c6580a07
go: downloading github.com/jakecoffman/cron v0.0.0-20190106200828-7e2009c226a5
go: downloading github.com/go-gomail/gomail v0.0.0-20160411212932-81ebce5c23df
go: downloading github.com/golang/protobuf v1.3.1
go: downloading github.com/Unknwon/com v0.0.0-20190321035513-0fed4efef755
go: downloading github.com/rakyll/statik v0.1.6
go: downloading github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: downloading github.com/go-xorm/builder v0.3.4
go: downloading github.com/klauspost/compress v1.5.0
go: downloading golang.org/x/sys v0.0.0-20190422165155-953cdadca894
go: downloading google.golang.org/genproto v0.0.0-20190530194941-fb225487d101
go: downloading golang.org/x/text v0.3.2
go: downloading github.com/klauspost/cpuid v1.2.1
# runtime
/usr/local/go/src/runtime/cpuflags_amd64.go:14:2: offsetX86HasAVX2 redeclared in this block
        previous declaration at /usr/local/go/src/runtime/cpuflags.go:14:37
/usr/local/go/src/runtime/mem_linux.go:20:6: sysAlloc redeclared in this block
        previous declaration at /usr/local/go/src/runtime/mem_aix.go:14:43
/usr/local/go/src/runtime/mem_linux.go:37:6: sysUnused redeclared in this block
        previous declaration at /usr/local/go/src/runtime/mem_aix.go:32:36
/usr/local/go/src/runtime/mem_linux.go:108:6: sysUsed redeclared in this block
        previous declaration at /usr/local/go/src/runtime/mem_aix.go:36:34
/usr/local/go/src/runtime/mem_linux.go:134:6: sysFree redeclared in this block
        previous declaration at /usr/local/go/src/runtime/mem_aix.go:42:52
/usr/local/go/src/runtime/mem_linux.go:139:6: sysFault redeclared in this block
        previous declaration at /usr/local/go/src/runtime/mem_aix.go:48:35
/usr/local/go/src/runtime/mem_linux.go:143:6: sysReserve redeclared in this block
        previous declaration at /usr/local/go/src/runtime/mem_aix.go:52:46
/usr/local/go/src/runtime/mem_linux.go:151:6: sysMap redeclared in this block
        previous declaration at /usr/local/go/src/runtime/mem_aix.go:60:51
/usr/local/go/src/runtime/netpoll_epoll.go:25:6: netpollinit redeclared in this block
        previous declaration at /usr/local/go/src/runtime/netpoll_aix.go:55:6
/usr/local/go/src/runtime/netpoll_epoll.go:39:6: netpolldescriptor redeclared in this block
        previous declaration at /usr/local/go/src/runtime/netpoll_aix.go:90:26
/usr/local/go/src/runtime/netpoll_epoll.go:39:6: too many errors
# math
/usr/local/go/src/math/trig_reduce.go:42:13: undefined: bits.Mul64
/usr/local/go/src/math/trig_reduce.go:43:16: undefined: bits.Mul64
/usr/local/go/src/math/trig_reduce.go:45:11: undefined: bits.Add64
/usr/local/go/src/math/trig_reduce.go:46:11: undefined: bits.Add64
makefile:23: recipe for target 'gocron' failed
make: *** [gocron] Error 2
root@iZj6chhgw5xb6zl7ohkzgrZ:~/go/src/github.com/ouqiang/gocron# make
go build  -o bin/gocron ./cmd/gocron
# runtime
/usr/local/go/src/runtime/cpuflags_amd64.go:14:2: offsetX86HasAVX2 redeclared in this block
        previous declaration at /usr/local/go/src/runtime/cpuflags.go:14:37
/usr/local/go/src/runtime/mem_linux.go:20:6: sysAlloc redeclared in this block
        previous declaration at /usr/local/go/src/runtime/mem_aix.go:14:43
/usr/local/go/src/runtime/mem_linux.go:37:6: sysUnused redeclared in this block
        previous declaration at /usr/local/go/src/runtime/mem_aix.go:32:36
/usr/local/go/src/runtime/mem_linux.go:108:6: sysUsed redeclared in this block
        previous declaration at /usr/local/go/src/runtime/mem_aix.go:36:34
/usr/local/go/src/runtime/mem_linux.go:134:6: sysFree redeclared in this block
        previous declaration at /usr/local/go/src/runtime/mem_aix.go:42:52
/usr/local/go/src/runtime/mem_linux.go:139:6: sysFault redeclared in this block
        previous declaration at /usr/local/go/src/runtime/mem_aix.go:48:35
/usr/local/go/src/runtime/mem_linux.go:143:6: sysReserve redeclared in this block
        previous declaration at /usr/local/go/src/runtime/mem_aix.go:52:46
/usr/local/go/src/runtime/mem_linux.go:151:6: sysMap redeclared in this block
        previous declaration at /usr/local/go/src/runtime/mem_aix.go:60:51
/usr/local/go/src/runtime/netpoll_epoll.go:25:6: netpollinit redeclared in this block
        previous declaration at /usr/local/go/src/runtime/netpoll_aix.go:55:6
/usr/local/go/src/runtime/netpoll_epoll.go:39:6: netpolldescriptor redeclared in this block
        previous declaration at /usr/local/go/src/runtime/netpoll_aix.go:90:26
/usr/local/go/src/runtime/netpoll_epoll.go:39:6: too many errors
# math
/usr/local/go/src/math/trig_reduce.go:42:13: undefined: bits.Mul64
/usr/local/go/src/math/trig_reduce.go:43:16: undefined: bits.Mul64
/usr/local/go/src/math/trig_reduce.go:45:11: undefined: bits.Add64
/usr/local/go/src/math/trig_reduce.go:46:11: undefined: bits.Add64
makefile:23: recipe for target 'gocron' failed
make: *** [gocron] Error 2
root@iZj6chhgw5xb6zl7ohkzgrZ:~/go/src/github.com/ouqiang/gocron# make

**Comment by luowei729** [comment]
使用过程中有些问题给你反馈下：
![image](https://user-images.githubusercontent.com/10611605/59451968-4ac4b500-8e3f-11e9-9e26-c3fe2905441f.png)
设置任务不限制执行时长值为0时，任务达到86400时会强制结束，意味着任务最多只能执行24小时后自动强制结束，没有不限制。
![image](https://user-images.githubusercontent.com/10611605/59452167-b60e8700-8e3f-11e9-9329-3d3dab28832f.png)
在执行中的任务需要实时能够观看执行日志，现在只能在结束后才能看日志
![image](https://user-images.githubusercontent.com/10611605/59452285-f241e780-8e3f-11e9-87a3-e8646f493081.png)
手动停止的任务不能看到执行日志
