### ISSUE TITLE
节点连接配置问题

### ISSUE THREAD

**Issue by wuyonghai** [ouqiang/gocron#146]
安装linux二进制包后，配置节点，选择127.0.0.1，然后在节点界面操作测试连接返回 连接失败-无法连接远程服务器，但是telnet 120.0.0.1 80 则能。能指导下么

**Comment by wuyonghai** [comment]
gocron-v1.5.1-linux-amd64.tar.gz

**Comment by ouqiang** [comment]
gocron-node默认监听的是5921端口

**Comment by wuyonghai** [comment]
> gocron-node默认监听的是5921端口

本地5921端口开启，也找tls安全认证了，但是还是无法连接远程服务器

**Comment by intelyt** [comment]
我用nodejs 修改了部分界面    希望能够使用  statik -src= resourceurl 重新编译成二进制 把 statik.go重新替换,请问  "resourceurl" 是那个文件夹

**Comment by ouqiang** [comment]
@wuyonghai ，请按照README文档安装

**Comment by ouqiang** [comment]
@intelyt，静态文件生成二进制

```bash
make statik
```

**Comment by intelyt** [comment]
谢谢
