### ISSUE TITLE
添加shell任务提示无法验证窗口

### ISSUE THREAD

**Issue by yan6996** [ouqiang/gocron#148]
表单验证失败, 请检测输入

/usr/bin/php /home/www/note.airmore.cn/index.php api/note/cronSendRemind >>/var/log/cron_airmore_note 2>&1
/usr/bin/php /home/www/mindmap.airmore.com/api/artisan schedule:run >>/dev/null 2>&1
/usr/bin/php /home/www/ts.lightmv.com/tikerMonitor.php >>/home/www/ts.lightmv.com/logs/restart.log

**Comment by ouqiang** [comment]
命令太长
