### ISSUE TITLE
新增定时任务时shell命令提示错误

### ISSUE THREAD

**Issue by yan6996** [ouqiang/gocron#149]
![image](https://user-images.githubusercontent.com/31616240/59517871-19a7bb80-8ef7-11e9-8661-ab64320216f3.png)
所有的脚本是正常的，每行代码如果不放在一起，单独一个任务是可以添加的，但是放在一个任务里面，就会报这种错误，很头痛，排除了很久也不知道什么问题，文档中也没有明确格式要求和提示，

**Comment by ouqiang** [comment]
这不是有效的shell命令哈, shell命令分隔是`;`, 这里输入的是shell命令，不是脚本

**Comment by yan6996** [comment]
那就是说我调用shell命令去执行php的脚本不行吗？这个shell命令，并不是代表所有在shell下能执行的命令对吗？

**Comment by yan6996** [comment]
还有就是，我把这个出问题的脚本php这一行放到新增的任务中添加又可以，

**Comment by ouqiang** [comment]
[文档](https://github.com/ouqiang/gocron/wiki/%E5%AE%9A%E6%97%B6%E4%BB%BB%E5%8A%A1)

**Comment by yan6996** [comment]
![捕获](https://user-images.githubusercontent.com/31616240/59522037-51ffc780-8f00-11e9-9708-2c6d532fbd10.JPG)
您看这条记录，也是php的脚本，但是执行是正常的 ，是不是那个表单验证需要调整，还有就是，验证失败，并没有日志记录，是验证哪条失败，是不是可以改进一下

**Comment by yan6996** [comment]
![image](https://user-images.githubusercontent.com/31616240/59522486-64c6cc00-8f01-11e9-9d99-1359dc2a3f5e.png)
这是我其中一条php的执行记录，是成功的，是不是那个表单验证需要调整一下，验证失败也没有提示哪一条验证有问题，我觉得是否可以改进一下
