### ISSUE TITLE
shell命令无法执行

### ISSUE THREAD

**Issue by LFasMike** [ouqiang/gocron#153]
按照说明文档安装启动成功。执行shell命令报错，信息如下：
INFO[2369] execute cmd start: [id: 9 cmd: ps aux | grep gocron]
INFO[2369] execute cmd end: [id: 9 cmd: ps aux | grep gocron err: ]

INFO[2817] execute cmd start: [id: 10 cmd: pwd]
INFO[2817] execute cmd end: [id: 10 cmd: pwd err: ]

**Comment by ouqiang** [comment]
错误是什么

**Comment by LFasMike** [comment]
> 错误是什么

刚调试了下    没报错  是没有输出执行完的output

**Comment by LFasMike** [comment]
感谢及时回复～
