### ISSUE TITLE
是否允许基于贵项目开发一个letsencrypt证书申请并自动部署的产品

### ISSUE THREAD

**Issue by shouyong** [ouqiang/gocron#166]
最初打算基于beego开发，后来发现了你这个项目。仔细评估后想基于你这个项目来做，目前核心架构与代码基本搭建好了，readme、test等都还没有来得及修改。仓库地址(暂时，后期可能会迁移到gitee)：https://github.com/shouyong/goautocert

我没有发现贵项目的开源协议，所以只能在此寻求授权。不知道我的这个软件是否有**侵犯你的权利**？

我基于下面考虑做成的决定：

1. 都有定时任务；
2. 现在使用贵项目做定时任务，没有必要再部署一个ssl证书管理系统，即使是部署最终还是要用这个你这个项目来做定时调用。

**Comment by ouqiang** [comment]
MIT协议，没有限制
