### ISSUE TITLE
gocron-node存在执行漏洞

### ISSUE THREAD

**Issue by auv51357** [ouqiang/gocron#168]
假设管理员密码被入侵的情况下,修改webUI的shell语句,可以导致worker执行超级权限下的构造的命令
例如运行windows目录的所有程序, 该动作可以被完美复现,例如运行注册表

建议修补方式:
gocron-node 增加开关 
-allowPATH  仅允许执行某个目录的命令
-allowExt      仅允许执行扩展名的指令

例如 
仅允许运行 C:\1文件夹下的bat文件: 
-allowPATH c:\1  -allowExt  bat

**Comment by ouqiang** [comment]
不要用管理员运行，Linux版本是默认禁止使用root账户启动gocron-node的

**Comment by auv51357** [comment]
我编译成功,在win下运行后,测试连接 web 页面报错
bind: Only one usage of each socket address (protocol/network address/port) is normally permitted." 
gocron-node  中显示
time="2019-08-18T20:02:07+08:00" level=info msg="execute cmd start: [id: 0 cmd:
echo hello]"
time="2019-08-18T20:02:07+08:00" level=info msg="execute cmd end: [id: 0 cmd: ec
ho hello err: exit status 1]"

而且替换了你发布的程序也出错,感觉网络模块有问题,我找了一圈,说是端口占用,但是并没发现

**Comment by ouqiang** [comment]
看提示好像是端口被占用了
