### ISSUE TITLE
请问接受的日志数据太大怎么解决？

### ISSUE THREAD

**Issue by sunlbs** [ouqiang/gocron#170]
请问接受的日志数据太大怎么解决？，我现在任务执行的时候每次都是这个问题，尝试过减少脚本执行时间，但是还是有问题。
![image](https://user-images.githubusercontent.com/14084759/63591256-cdf14c80-c5e0-11e9-9f5a-543791c4b5be.png)

**Comment by ouqiang** [comment]
日志写入文件中，数据库任务日志只保留必要的执行过程。

**Comment by cossbow** [comment]
可以启用日志压缩不？

**Comment by ouqiang** [comment]
大量的日志不适合保存到MySQL，可以写入文件中，MySQL只保留关键步骤。
