### ISSUE TITLE
执行go run gocron.go web 返回exit status 1

### ISSUE THREAD

**Issue by Enssie** [ouqiang/gocron#18]
请教！！运行到/urfave/cli/app.go 487行 a(context) 突然跳出是什么问题呀。。。

**Comment by ouqiang** [comment]
没有错误信息吗, [编译安装文档](https://github.com/ouqiang/gocron#源码安装)
错误会输出到终端或log/cron.log

**Comment by Enssie** [comment]
感谢感谢！没有conf目录。。我以为自动生成的😅
