### ISSUE TITLE
任务被强制结束

### ISSUE THREAD

**Issue by 52Lau** [ouqiang/gocron#186]
定时执行爬虫任务
QidianlifeApp
状态：失败--主机: [子节点1-49.235.48.249:5921]
执行超时, 强制结束

![image](https://user-images.githubusercontent.com/37538641/68074129-c31e1980-fdd2-11e9-8346-edbfefbf1caa.png)

**Comment by ouqiang** [comment]
有没有设置超时时间。默认超时时间是24小时。

**Comment by 52Lau** [comment]
嗯，一些命令要管理员账号的时候是怎么弄呢，现在是用普通用户启动子节点的

**Comment by ouqiang** [comment]
用root账号启动gocron-node

**Comment by 52Lau** [comment]
![image](https://user-images.githubusercontent.com/37538641/68215063-8db73d00-0019-11ea-8dce-e9f810d98e40.png)
但是会遇到这个问题，所以采用普通用户启动，但是普通用户，执行某些命令的时候，就不对 了

**Comment by ouqiang** [comment]
-h 查看帮助
