### ISSUE TITLE
运行脚本一直超时

### ISSUE THREAD

**Issue by 52Lau** [ouqiang/gocron#188]
一个脚本会一直输出很多内容，所以会
rpc error: code = ResourceExhausted desc = grpc: received message larger than max (7253091 vs. 4194304)
一般脚本用nohup 运行的时候，也会一直不结束
想问问有没有什么方法可以解决的这种问题

**Comment by ouqiang** [comment]
脚本输出内容太多了，写入文件中，数据库只保留关键步骤。

**Comment by 52Lau** [comment]
好的，感谢
