### ISSUE TITLE
源码编译失败

### ISSUE THREAD

**Issue by shuyabin** [ouqiang/gocron#2]
大腿你好 @ouqiang 
![image](https://cloud.githubusercontent.com/assets/14884581/26134724/31b29b42-3ae3-11e7-8b20-059d7e30de10.png)
![image](https://cloud.githubusercontent.com/assets/14884581/26134727/37e5a2c0-3ae3-11e7-9116-3abb202a44be.png)

**Comment by shuyabin** [comment]
已经解决.

**Comment by Yves-yuan** [comment]
@shuyabin  我尝试在windows下使用make package-all打包，但是失败了，请问您是怎么打包的呢？
