### ISSUE TITLE
执行HTTP请求错误-Get https://xxxxx/public/getapi: net/http: TLS handshake timeout

### ISSUE THREAD

**Issue by aminsire** [ouqiang/gocron#20]
我这是采集页面，可能有些时间会比较久，好多都失败，打开就显示

执行HTTP请求错误-Get https://xxxxx/public/getapi: net/http: TLS handshake timeout

![cj1](https://user-images.githubusercontent.com/32963460/31831423-0c58b5a0-b5f6-11e7-891c-9dc5fc74c458.png)

**Comment by ouqiang** [comment]
可能是网络不稳定，自己写程序请求目标URL，看是否能正常响应，再做判断。
