### ISSUE TITLE
您好，请问HTTP请求能否加入更丰富的功能

### ISSUE THREAD

**Issue by kxy000** [ouqiang/gocron#215]
您好，请问HTTP请求能否更丰富些，header 定义,http状态判断，期望返回值等，来判别http任务的执行结果,方便直接执行一些http请求逻辑。再次感谢您提供这么好的开源工具。

**Comment by ouqiang** [comment]
可以通过shell自己实现哈

**Comment by kxy000** [comment]
哈哈 ok 再次感谢
