### ISSUE TITLE
日志打印过多，gocron认为失败

### ISSUE THREAD

**Issue by TroubleJin** [ouqiang/gocron#216]
rpc error: code = ResourceExhausted desc = grpc: received message larger than max (12623738 vs. 4194304)

**Comment by ouqiang** [comment]
不支持超过4M的输出哈，存入数据库要炸了。

**Comment by qifengzhang007** [comment]
我刚使用，发现也是结果显示失败了，
我看了一下日子都是成功执行，
但是日志确实有点多，应该是超过4M了。
我这边的定时任务目前全靠系统的crontab。
每天的数据生成量在80w左右，
日志确实很多，看来我要想别的办法了。

**Comment by ouqiang** [comment]
日志写入文件，执行的关键步骤输出到stdout，方便在管理后台查看。

**Comment by mgaic** [comment]
> 日志写入文件，执行的关键步骤输出到stdout，方便在管理后台查看。

如果日志过大， 超出了阈值， 整个任务会被kill 吗
