### ISSUE TITLE
请教一下 webhook的模板配置问题

### ISSUE THREAD

**Issue by MQL9011** [ouqiang/gocron#217]
我任务执行成功后通过wehook中的URL来发消息。

消息是利用了'server酱'

但是模板中填写的字段，并没有变成请求的参数，所以请教一下模板中该如何写？

**Comment by ouqiang** [comment]
模板发出来看下

**Comment by MQL9011** [comment]
<img width="487" alt="截屏2020-04-15下午10 14 19" src="https://user-images.githubusercontent.com/11871158/79347741-9b78d300-7f66-11ea-92fc-f5a90cc09987.png">

不太明白模板中的参数该如何写.
