### ISSUE TITLE
rpc error

### ISSUE THREAD

**Issue by skyclub66** [ouqiang/gocron#22]
rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (40254453 vs. 4194304)
主机: [localhost-127.0.0.1]
rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (40254453 vs. 4194304)

再次讨教下,我的爬虫任务执行一段时间就这个样子 搞不清楚什么问题，刚部署的时候还是ok的

**Comment by ouqiang** [comment]
任务执行结果返回值超过了4M的限制

**Comment by ouqiang** [comment]
IP隐藏掉再发图

**Comment by skyclub66** [comment]
那是执行成功了 是吧

**Comment by ouqiang** [comment]
根据错误信息只能得出消息大小超过了限制，具体业务执行是否成功，无法知道。

**Comment by skyclub66** [comment]
好的 谢谢

**Comment by BabyCY** [comment]
> 任务执行结果返回值超过了4M的限制

这个4M的限制在哪里可以修改或者裁剪？ 因为我们必须要监控到log的状况，很多都超过了这个大小
