### ISSUE TITLE
请问如果把节点部署到外网服务器会不会有安全问题？

### ISSUE THREAD

**Issue by BabyCY** [ouqiang/gocron#220]
貌似在后台可以随意添加节点，也没看到有啥校验，如果我在后台添加一个别人的服务器节点，是不是可以做坏事？求解

**Comment by ouqiang** [comment]
[HTTPS双向认证](https://github.com/ouqiang/gocron/wiki/%E5%AE%89%E5%85%A8-TLS%E5%8F%8C%E5%90%91%E8%AE%A4%E8%AF%81)
