### ISSUE TITLE
关于webhook发送通知

### ISSUE THREAD

**Issue by liyanxia** [ouqiang/gocron#226]
没有看到日志报错，也没接收到webhook发出的通知

**Comment by ouqiang** [comment]
通知发送失败会记录日志，你可以使用debug模式启动，看下有没有更详细的日志。

**Comment by liyanxia** [comment]
没有发现更详细的日志,看webhook http请求之后返回也是200，你之前是测试可以吗？

**Comment by ouqiang** [comment]
你可以输出webhook请求body，看下是否正常，如果正常那就是发送通知的程序有问题。

**Comment by czxin788** [comment]
> 你可以输出webhook请求body，看下是否正常，如果正常那就是发送通知的程序有问题。

我看了我发的body体正常，发送通知的程序有问题，我该怎么解决
