### ISSUE TITLE
shell 执行方式的命令有什么限制吗

### ISSUE THREAD

**Issue by 576272014** [ouqiang/gocron#230]
我创建执行方式为 shell 的任务，在命令栏输入命令一，可以正常保存任务；输入命令二，保存时提示“表单检测失败，请验证输入。”

命令一：
#!/usr/bin/sh
day=`date -d "180 days ago" +%Y%m%d`
index=$(curl -XGET -u elastic:pwd 'http://192.168.1.10:9200/_cat/indices?v&s=index' | grep close | grep $day | awk '{print $2}')
for i in $index
do
  echo $i
done

命令二：
#!/usr/bin/sh
day=`date -d "180 days ago" +%Y%m%d`
index=$(curl -XGET -u elastic:pwd 'http://192.168.1.10:9200/_cat/indices?v&s=index' | grep close | grep $day | awk '{print $2}')
for i in $index
do
  echo $i
  curl -XGET -u elastic:pwd "http://192.168.1.10:9200/$i"
done

命令二就比命令一在 for 循环 do 里加了一条命令。
以上两个命令我在 linux 机器上都可以执行成功。
我已尝试过更换单引号和双引号，但是无效。
请教大佬，shell 执行方式的命令有什么限制吗？我要填入命令二，怎么才能保存。

**Comment by ouqiang** [comment]
只支持单条命令哈， 复杂命令写入脚本中执行。
