### ISSUE TITLE
手工执行UPDATE `task_log` SET可以成功，但是gocron自己执行报错

### ISSUE THREAD

**Issue by czxin788** [ouqiang/gocron#232]
[root@zabbix-server log]# tail cron.log 
2020-05-26/11:45:35 [ERR] 编辑任务#获取任务详情失败#任务ID-0
2020-05-26/11:46:59 [INF] 开始执行任务#bj-his-test-expdp.sh#命令-su - oracle -lc "/usr/local/shell/expdp.sh"
2020-05-26/11:56:16 [INF] 任务完成#bj-his-test-expdp.sh#命令-su - oracle -lc "/usr/local/shell/expdp.sh"
2020-05-26/11:56:16 [ERR] [[任务结束#更新任务日志失败- Error 1366: Incorrect string value: '\xD5\xEF\xB6\xCF" ...' for column 'result' at row 1]]
2020-05-26/12:31:25 [INF] 开始执行任务#bj-his-test-expdp.sh#命令-su - oracle -lc "/usr/local/shell/expdp.sh"
2020-05-26/12:34:07 [INF] 任务完成#bj-his-test-expdp.sh#命令-su - oracle -lc "/usr/local/shell/expdp.sh"
2020-05-26/12:34:07 [ERR] [[任务结束#更新任务日志失败- Error 1366: Incorrect string value: '\xD5\xEF\xB6\xCF" ...' for column 'result' at row 1]]
2020-05-26/12:50:26 [INF] 开始执行任务#bj-his-test-expdp.sh#命令-su - oracle -lc "/usr/local/shell/expdp.sh"
2020-05-26/12:52:51 [INF] 任务完成#bj-his-test-expdp.sh#命令-su - oracle -lc "/usr/local/shell/expdp.sh"
2020-05-26/12:52:51 [ERR] [[任务结束#更新任务日志失败- Error 1366: Incorrect string value: '\xD5\xEF\xB6\xCF" ...' for column 'result' at row 1]]

手工执行下面这个sql是可以成功的，为什么gocron自己执行报错：

UPDATE `task_log` SET `retry_times` = 0, `status` = 2, `result` = '主机: [bj-his-test-172.xxxxx:5921]\n\n\nExport: Release 11.2.0.4.0 - Production on Tue May 26 12:50:26 2020\n\nCopyright (c) 1982, 2011, Oracle and/or its affiliates.  All rights reserved.\n\nConnected to: Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production\nWith the Partitioning, OLAP, Data Mining and Real Application Testing options\nFLASHBACK automatically enabled to preserve database integrity.\nStarting \"SYS\".\"SYS_EXPORT_SCHEMA_01\":  \"/******** AS SYSDBA\" directory=DATA_DIR Dumpfile=appuser_local_20200526_125026.dmp LOGFILE=appuser_local_20200526_125026.log schemas=appuser compression=all \nEstimate in progress using BLOCKS method...\nProcessing object type SCHEMA_EXPORT/TABLE/TABLE_DATA\nTotal estimation using BLOCKS method: 7.367 GB\nProcessing object type SCHEMA_EXPORT/USER\nProcessing object type SCHEMA_EXPORT/SYSTEM_GRANT\nProcessing object type SCHEMA_EXPORT/ROLE_GRANT\nProcessing object type SCHEMA_EXPORT/DEFAULT_ROLE\nProcessing object type SCHEMA_EXPORT/PRE_SCHEMA/PROCACT_SCHEMA\nProcessing object type SCHEMA_EXPORT/SYNONYM/SYNONYM\nProcessing object type SCHEMA_EXPORT/TYPE/TYPE_SPEC\nProcessing object type SCHEMA_EXPORT/SEQUENCE/SEQUENCE\nProcessing object type SCHEMA_EXPORT/TABLE/TABLE\nProcessing object type SCHEMA_EXPORT/TABLE/COMMENT\nProcessing object type SCHEMA_EXPORT/PACKAGE/PACKAGE_SPEC\nProcessing object type SCHEMA_EXPORT/FUNCTION/FUNCTION\nProcessing object type SCHEMA_EXPORT/PROCEDURE/PROCEDURE\nProcessing object type SCHEMA_EXPORT/PACKAGE/COMPILE_PACKAGE/PACKAGE_SPEC/ALTER_PACKAGE_SPEC\nProcessing object type SCHEMA_EXPORT/FUNCTION/ALTER_FUNCTION\nProcessing object type SCHEMA_EXPORT/PROCEDURE/ALTER_PROCEDURE\nProcessing object type SCHEMA_EXPORT/TABLE/INDEX/INDEX\nProcessing object type SCHEMA_EXPORT/TABLE/INDEX/FUNCTIONAL_INDEX/INDEX\nProcessing object type SCHEMA_EXPORT/TABLE/CONSTRAINT/CONSTRAINT\nProcessing object type SCHEMA_EXPORT/TABLE/INDEX/STATISTICS/INDEX_STATISTICS\nProcessing object type SCHEMA_EXPORT/TABLE/INDEX/STATISTICS/FUNCTIONAL_INDEX/INDEX_STATISTICS\nProcessing object type SCHEMA_EXPORT/VIEW/VIEW\nProcessing object type SCHEMA_EXPORT/VIEW/COMMENT\nProcessing object type SCHEMA_EXPORT/PACKAGE/PACKAGE_BODY\nProcessing object type SCHEMA_EXPORT/TABLE/CONSTRAINT/REF_CONSTRAINT\nProcessing object type SCHEMA_EXPORT/TABLE/TRIGGER\nProcessing object type SCHEMA_EXPORT/TABLE/STATISTICS/TABLE_STATISTICS\n. . exported \"appuser\".\"EXTEND_MONITOR_ACCESS_RECORDS\"  817.3 MB  359438 rows\n. . exported \"appuser\".\"BAS_TASK_LOGS\"                  137.8 MB 5311296 rows\n. . exported \"appuser\".\"INS_MEDLIST_YB1023\"             29.30 MB  765537 rows\n. . exported \"appuser\".\"PAY_TRANSACTION_DETAIL20191028\"  7.634 MB   69943 rows\n. . exported \"SYS\".\"SYS_EXPORT_SCHEMA_01\" successfully loaded/unloaded\n******************************************************************************\nDump file set for SYS.SYS_EXPORT_SCHEMA_01 is:\n  /data/backup/appuser_local_20200526_125026.dmp\nJob \"SYS\".\"SYS_EXPORT_SCHEMA_01\" successfully completed at Tue May 26 12:52:50 2020 elapsed 0 00:02:24\n\n\n\n', `end_time` = '2020-05-26 12:52:51' WHERE `id`=86

**Comment by ouqiang** [comment]
可能是包含非utf8字符

**Comment by czxin788** [comment]
> 可能是包含非utf8字符

手工在mysql里面可以执行成功，但是gocron自己不能执行，报ncorrect string value: '\xD5\xEF\xB6\xCF" ...' for column 'result' at row 1]

我应该怎么解决呢

**Comment by czxin788** [comment]
这是我用dev模式启动的gocron，输出如下内容，感觉是gocron程序的问题，但是不知道怎么解决。


[BEGIN] 2020/5/26 15:43:09
[Macaron] 2020-05-26 15:41:38: Started GET /api/task/log?page_size=20&page=1&task_id=&protocol=&status= for 219.143.183.2
[Macaron] 2020-05-26 15:41:38: Started GET /api/task/log?page_size=20&page=1&task_id=&protocol=&status= for 219.143.183.2
[xorm] [info]  2020/05/26 15:41:38.822177 [SQL] SELECT count(*) FROM `task_log`
[xorm] [info]  2020/05/26 15:41:38.822330 [SQL] SELECT `id`, `task_id`, `name`, `spec`, `protocol`, `command`, `timeout`, `retry_times`, `hostname`, `start_time`, `end_time`, `status`, `result` FROM `task_log` ORDER BY `id` DESC LIMIT 20
[Macaron] 2020-05-26 15:41:38: Completed GET /api/task/log?page_size=20&page=1&task_id=&protocol=&status= 200 OK in 387.278µs
[Macaron] 2020-05-26 15:41:38: Completed GET /api/task/log?page_size=20&page=1&task_id=&protocol=&status= 200 OK in 426.684µs
[Macaron] 2020-05-26 15:41:39: Started GET /api/task/log?page_size=20&page=1&task_id=&protocol=&status= for 219.143.183.2
[Macaron] 2020-05-26 15:41:39: Started GET /api/task/log?page_size=20&page=1&task_id=&protocol=&status= for 219.143.183.2
[xorm] [info]  2020/05/26 15:41:39.395010 [SQL] SELECT count(*) FROM `task_log`
[xorm] [info]  2020/05/26 15:41:39.395146 [SQL] SELECT `id`, `task_id`, `name`, `spec`, `protocol`, `command`, `timeout`, `retry_times`, `hostname`, `start_time`, `end_time`, `status`, `result` FROM `task_log` ORDER BY `id` DESC LIMIT 20
[Macaron] 2020-05-26 15:41:39: Completed GET /api/task/log?page_size=20&page=1&task_id=&protocol=&status= 200 OK in 344.35µs
[Macaron] 2020-05-26 15:41:39: Completed GET /api/task/log?page_size=20&page=1&task_id=&protocol=&status= 200 OK in 392.333µs
[Macaron] 2020-05-26 15:41:46: Started GET /api/task/log?page_size=20&page=1&task_id=&protocol=&status= for 219.143.183.2
[Macaron] 2020-05-26 15:41:46: Started GET /api/task/log?page_size=20&page=1&task_id=&protocol=&status= for 219.143.183.2
[xorm] [info]  2020/05/26 15:41:46.457141 [SQL] SELECT count(*) FROM `task_log`
[xorm] [info]  2020/05/26 15:41:46.457331 [SQL] SELECT `id`, `task_id`, `name`, `spec`, `protocol`, `command`, `timeout`, `retry_times`, `hostname`, `start_time`, `end_time`, `status`, `result` FROM `task_log` ORDER BY `id` DESC LIMIT 20
[Macaron] 2020-05-26 15:41:46: Completed GET /api/task/log?page_size=20&page=1&task_id=&protocol=&status= 200 OK in 437.398µs
[Macaron] 2020-05-26 15:41:46: Completed GET /api/task/log?page_size=20&page=1&task_id=&protocol=&status= 200 OK in 493.849µs
[xorm] [info]  2020/05/26 15:41:58.994564 PING DATABASE mysql
[xorm] [info]  2020/05/26 15:42:00.000194 [SQL] INSERT INTO `task_log` (`task_id`,`name`,`spec`,`protocol`,`command`,`timeout`,`retry_times`,`hostname`,`start_time`,`end_time`,`status`,`result`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) []interface {}{4, "bj-his-test-expdp.sh", "0 42 15 * * *", 2, "su - oracle -lc \"/usr/local/shell/expdp.sh\"", 0, 0, "bj-his-test - 172.17.28.44<br>", "2020-05-26 15:42:00", "2020-05-26 15:42:00", 1, ""}
2020-05-26/15:42:00 [DBG] #/Users/apple/project/github-project/golang/src/github.com/ouqiang/gocron/internal/service/task.go#github.com/ouqiang/gocron/internal/service.beforeExecJob#373行#任务命令-su - oracle -lc "/usr/local/shell/expdp.sh"
2020-05-26/15:42:00 [INF] #/Users/apple/project/github-project/golang/src/github.com/ouqiang/gocron/internal/service/task.go#github.com/ouqiang/gocron/internal/service.createJob.func1#341行#开始执行任务#bj-his-test-expdp.sh#命令-su - oracle -lc "/usr/local/shell/expdp.sh"
[Macaron] 2020-05-26 15:42:35: Started GET /api/task/log?page_size=20&page=1&task_id=&protocol=&status= for 219.143.183.2
[Macaron] 2020-05-26 15:42:35: Started GET /api/task/log?page_size=20&page=1&task_id=&protocol=&status= for 219.143.183.2
[xorm] [info]  2020/05/26 15:42:35.879939 [SQL] SELECT count(*) FROM `task_log`
[xorm] [info]  2020/05/26 15:42:35.880163 [SQL] SELECT `id`, `task_id`, `name`, `spec`, `protocol`, `command`, `timeout`, `retry_times`, `hostname`, `start_time`, `end_time`, `status`, `result` FROM `task_log` ORDER BY `id` DESC LIMIT 20
[Macaron] 2020-05-26 15:42:35: Completed GET /api/task/log?page_size=20&page=1&task_id=&protocol=&status= 200 OK in 657.652µs
[Macaron] 2020-05-26 15:42:35: Completed GET /api/task/log?page_size=20&page=1&task_id=&protocol=&status= 200 OK in 793.161µs
[xorm] [info]  2020/05/26 15:43:28.994566 PING DATABASE mysql
2020-05-26/15:44:24 [INF] #/Users/apple/project/github-project/golang/src/github.com/ouqiang/gocron/internal/service/task.go#github.com/ouqiang/gocron/internal/service.createJob.func1#343行#任务完成#bj-his-test-expdp.sh#命令-su - oracle -lc "/usr/local/shell/expdp.sh"
[xorm] [info]  2020/05/26 15:44:24.581898 [SQL] UPDATE `task_log` SET `retry_times` = ?, `status` = ?, `result` = ?, `end_time` = ? WHERE `id`=? []interface {}{0, 2, "主机: [bj-his-test-172.17.28.44:5921]\n\n\nExport: Release 11.2.0.4.0 - Production on Tue May 26 15:42:00 2020\n\nCopyright (c) 1982, 2011, Oracle and/or its affiliates.  All rights reserved.\n\nConnected to: Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production\nWith the Partitioning, OLAP, Data Mining and Real Application Testing options\nFLASHBACK automatically enabled to preserve database integrity.\nStarting \"SYS\".\"SYS_EXPORT_SCHEMA_01\":  \"/******** AS SYSDBA\" directory=DATA_DIR Dumpfile=appuser_local_20200526_154200.dmp LOGFILE=appuser_local_20200526_154200.log schemas=appuser compression=all \nEstimate in progress using BLOCKS method...\nProcessing object type SCHEMA_EXPORT/TABLE/TABLE_DATA\nTotal estimation using BLOCKS method: 7.368 GB\nProcessing object type SCHEMA_EXPORT/USER\nProcessing object type SCHEMA_EXPORT/SYSTEM_GRANT\nProcessing object type SCHEMA_EXPORT/ROLE_GRANT\nProcessing object type SCHEMA_EXPORT/DEFAULT_ROLE\nProcessing object type SCHEMA_EXPORT/PRE_SCHEMA/PROCACT_SCHEMA\nProcessing object type SCHEMA_EXPORT/SYNONYM/SYNONYM\nProcessing object type SCHEMA_EXPORT/TYPE/TYPE_SPEC\nProcessing object type SCHEMA_EXPORT/SEQUENCE/SEQUENCE\nProcessing object type SCHEMA_EXPORT/TABLE/TABLE\nProcessing object type SCHEMA_EXPORT/TABLE/COMMENT\nProcessing object type SCHEMA_EXPORT/PACKAGE/PACKAGE_SPEC\nProcessing object type SCHEMA_EXPORT/FUNCTION/FUNCTION\nProcessing object type SCHEMA_EXPORT/PROCEDURE/PROCEDURE\nProcessing object type SCHEMA_EXPORT/PACKAGE/COMPILE_PACKAGE/PACKAGE_SPEC/ALTER_PACKAGE_SPEC\nProcessing object type SCHEMA_EXPORT/FUNCTION/ALTER_FUNCTION\nProcessing object type SCHEMA_EXPORT/PROCEDURE/ALTER_PROCEDURE\nProcessing object type SCHEMA_EXPORT/TABLE/INDEX/INDEX\nProcessing object type SCHEMA_EXPORT/TABLE/INDEX/FUNCTIONAL_INDEX/INDEX\nProcessing object type SCHEMA_EXPORT/TABLE/CONSTRAINT/CONSTRAINT\nProcessing object type SCHEMA_EXPORT/TABLE/INDEX/STATISTICS/INDEX_STATISTICS\nProcessing object type SCHEMA_EXPORT/TABLE/INDEX/STATISTICS/FUNCTIONAL_INDEX/INDEX_STATISTICS\nProcessing object type SCHEMA_EXPORT/VIEW/VIEW\nProcessing object type SCHEMA_EXPORT/VIEW/COMMENT\nProcessing object type SCHEMA_EXPORT/PACKAGE/PACKAGE_BODY\nProcessing object type SCHEMA_EXPORT/TABLE/CONSTRAINT/REF_CONSTRAINT\nProcessing object type SCHEMA_EXPORT/TABLE/TRIGGER\nProcessing object type SCHEMA_EXPORT/TABLE/STATISTICS/TABLE_STATISTICS\n. . exported \"appuser\".\"EXTEND_MONITOR_ACCESS_RECORDS\"  819.9 MB  360774 rows\n. . exported \"appuser\".\"BAS_TASK_LOGS\"                  137.9 MB 5314451 rows\n. . exported \"appuser\".\"INS_MEDLIST_YB1023\"             29.30 MB  765537 rows\n. . exported \"appuser\".\"INS_MEDLIST_YB102301\"           29.30 MB  765537 rows\n. . exported \"appuser\".\"PAY_TRANSACTION_DETAIL\"         16.56 MB  148205 rows\n. . exported \"appuser\".\"PAY_TRANSACTION_DETAIL_02\"      14.01 MB  125091 rows\n. . exported \"appuser\".\"PAY_TRANSACTION_DETAIL_copy1\"   13.11 MB  113605 rows\n. . exported \"appuser\".\"INS_REGIST_PATIENT_INFO\"        10.15 MB  349813 rows\n. . exported \"appuser\".\"PAY_TRANSACTION_DETAIL1111\"     8.262 MB   75361 rows\n. . exported \"appuser\".\"PAY_TRANSACTION_DETAIL1104\"     8.008 MB   73248 rows\n. . exported \"appuser\".\"PAY_TRANSACTION_DETAIL20191028\"  7.634 MB   69943 rows\n. . exported \"appuser\".\"PAY_TRANSACTION_DETAIL1022\"     7.343 MB   67275 rows\n. . exported \"appuser\".\"EXTEND_MONITOR_ACCESS_SQL\"      3.658 MB    3413 rows\n. . exported \"appuser\".\"INS_MEDLIST_YB\"                 5.177 MB  121706 rows\n. . exported \"appuser\".\"INS_MEDITEMLIST_YB1023\"         3.146 MB  122977 rows\n. . exported \"appuser\".\"INS_MEDITEMLIST_YB102301\"       3.146 MB  122977 rows\n. . exported \"appuser\".\"INP_ORDERS_EXC\"                 4.195 MB   89252 rows\n. . exported \"SYS\".\"SYS_EXPORT_SCHEMA_01\" successfully loaded/unloaded\n******************************************************************************\nDump file set for SYS.SYS_EXPORT_SCHEMA_01 is:\n  /data/backup/appuser_local_20200526_154200.dmp\nJob \"SYS\".\"SYS_EXPORT_SCHEMA_01\" successfully completed at Tue May 26 15:44:24 2020 elapsed 0 00:02:24\n\n\n\n", "2020-05-26 15:44:24", 208}
2020-05-26/15:44:24 [ERR] #/Users/apple/project/github-project/golang/src/github.com/ouqiang/gocron/internal/service/task.go#github.com/ouqiang/gocron/internal/service.afterExecJob#382行#[[任务结束#更新任务日志失败- Error 1366: Incorrect string value: '\xD5\xEF\xB6\xCF" ...' for column 'result' at row 1]]
[xorm] [info]  2020/05/26 15:44:58.994573 PING DATABASE mysql

[END] 2020/5/26 15:46:38

**Comment by ouqiang** [comment]
Error 1366: Incorrect string value

这个错误是字符集错误，gocron只支持utf8

**Comment by czxin788** [comment]
> Error 1366: Incorrect string value
> 
> 这个错误是字符集错误，gocron只支持utf8

已经确认数据库是ut8字符集

<root@localhost:mysql3306.sock [gocron]> \s
--------------
mysql  Ver 14.14 Distrib 5.7.22, for linux-glibc2.12 (x86_64) using  EditLine wrapper

Connection id:		6
Current database:	gocron
Current user:		root@localhost
SSL:			Not in use
Current pager:		stdout
Using outfile:		''
Using delimiter:	;
Server version:		5.7.22-log MySQL Community Server (GPL)
Protocol version:	10
Connection:		Localhost via UNIX socket
Server characterset:	utf8
Db     characterset:	utf8
Client characterset:	utf8
Conn.  characterset:	utf8
UNIX socket:		/data/mysql/mysql3306/tmp/mysql3306.sock
Uptime:			28 min 27 sec

Threads: 2  Questions: 656  Slow queries: 0  Opens: 129  Flush tables: 1  Open tables: 122  Queries per second avg: 0.384
--------------

<root@localhost:mysql3306.sock [gocron]> show create database gocron \G
*************************** 1. row ***************************
       Database: gocron
Create Database: CREATE DATABASE `gocron` /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci */
1 row in set (0.00 sec)


<root@localhost:mysql3306.sock [gocron]> show create table task_log \G
*************************** 1. row ***************************
       Table: task_log
Create Table: CREATE TABLE `task_log` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `task_id` int(11) NOT NULL DEFAULT '0',
  `name` varchar(32) NOT NULL,
  `spec` varchar(64) NOT NULL,
  `protocol` tinyint(4) NOT NULL,
  `command` varchar(256) NOT NULL,
  `timeout` mediumint(9) NOT NULL DEFAULT '0',
  `retry_times` tinyint(4) NOT NULL DEFAULT '0',
  `hostname` varchar(128) NOT NULL DEFAULT '',
  `start_time` datetime DEFAULT NULL,
  `end_time` datetime DEFAULT NULL,
  `status` tinyint(4) NOT NULL DEFAULT '1',
  `result` mediumtext NOT NULL,
  PRIMARY KEY (`id`),
  KEY `IDX_task_log_task_id` (`task_id`),
  KEY `IDX_task_log_protocol` (`protocol`),
  KEY `IDX_task_log_status` (`status`)
) ENGINE=InnoDB AUTO_INCREMENT=216 DEFAULT CHARSET=utf8
1 row in set (0.00 sec)

**Comment by czxin788** [comment]
我明白了，是expdp备份oracle数据库时，这个库里面的表名有中文导致的

**Comment by czxin788** [comment]
能不能再帮我看看，为啥我的钉钉收不到消息
https://github.com/ouqiang/gocron/issues/231
