### ISSUE TITLE
希望增加command字段的长度限制

### ISSUE THREAD

**Issue by jbinglei** [ouqiang/gocron#233]
当前command字段限制vchar256，稍微复杂一些的命令便保存失败。希望能够增加长度限制，或者允许自定义。

**Comment by 52Lau** [comment]
😄,可以写为一个sh脚本啊,命令里面调用脚本

**Comment by aeoluswing** [comment]
因为脚本写成了可以传入参数，增加了脚本的灵活性，因此很长的命令（带参数）就会导致超长。

我已经改造过这个问题，有四处：
1. models的task.go中修改command的映射类型，不要使用varchar(256)，可以用text或者mediumtext
2. 同样是models中的task_log.go修改command字段类型
3. 约束检查中调整最大值，如果是mediumtext最长限制应该调整为16777215
4. 对于已经发布的系统，修改数据库中对应的字段类型，ddl操作

注意：这种修改方式可以在保存定时任务时支持更长的shell任务，但执行是否成功还受限于agent所在环境的终端字符长度限制，因此建议调整成一样为好
