### ISSUE TITLE
计划任务都失败了，为啥gocron还鉴定执行状态为成功

### ISSUE THREAD

**Issue by czxin788** [ouqiang/gocron#238]
![image](https://user-images.githubusercontent.com/13861904/84125061-991a8d00-aa6e-11ea-88f3-9a3037e3e824.png)

**Comment by lxzchen** [comment]
“成功、失败”是调度本身的状态，而不是指执行任务的成功和失败。
要实现你的功能，似乎通过“关键字匹配通知”可以满足你的要求。

**Comment by czxin788** [comment]
> “成功、失败”是调度本身的状态，而不是指执行具体任务内容的成功和失败。
> 要实现你的功能，似乎通过“关键字匹配通知”可以满足你的要求。
> 具体是不是还是坐等作者来回答吧。

谢谢

**Comment by ouqiang** [comment]
shell脚本执行是否成功，是通过exit code，显然你的脚本返回的是0，即执行成功。
