### ISSUE TITLE
数据库配置写入文件失败

### ISSUE THREAD

**Issue by HyhBlazing** [ouqiang/gocron#239]
能链接到数据库，但是提交显示配置写入失败

**Comment by ouqiang** [comment]
截图看下，哪个提示的？

**Comment by HyhBlazing** [comment]
![hyh_2020-06-12_18-48-51](https://user-images.githubusercontent.com/40458321/84495897-93c37980-acde-11ea-9613-b9c5ce6fa160.png)
![hyh_2020-06-12_18-57-14](https://user-images.githubusercontent.com/40458321/84495905-96be6a00-acde-11ea-950a-3d1a13876a01.png)
本地的和RDS都不行。

**Comment by HyhBlazing** [comment]
成功了，是权限的问题，写入失败conf的文件夹权限是root，必须是www才可以
