### ISSUE TITLE
api 报{"err":1,"msg":"HTTP Error 403: Forbidden"}

### ISSUE THREAD

**Issue by wy281704862** [ouqiang/gocron#24]
![tim 20171117123021](https://user-images.githubusercontent.com/3655024/32929478-4294c138-cb93-11e7-8c41-c492ec330c00.png)

**Comment by ouqiang** [comment]
做权限控制时，没有把/api排除，将在下一版本中修复。

**Comment by ouqiang** [comment]
已修复
