### ISSUE TITLE
如果定时任务执行时间超过24小时任务会失败

### ISSUE THREAD

**Issue by HyhBlazing** [ouqiang/gocron#243]
任务执行超时强制结束, 取值0-86400(秒), 默认0, 不限制

不限制的话最长时间是86400秒，能否时间自定义更久？

**Comment by HyhBlazing** [comment]
老哥我有说明白咩，任务超时时间最多86400秒，可以设定无限制吗？

**Comment by ouqiang** [comment]
暂不支持
