### ISSUE TITLE
任务超时时间不能超过300

### ISSUE THREAD

**Issue by a717445834** [ouqiang/gocron#244]
提示中任务超时时间是0-86400，但是当输入大于300的数时候，会提示“HTTP任务超时时间不能超过300秒”

**Comment by ouqiang** [comment]
HTTP任务超时时间不能超过300

**Comment by shaveneLee** [comment]
> HTTP任务超时时间不能超过300

HTTP任务为啥只允许300s？能否适当加长限制，比如 2h

**Comment by a717445834** [comment]
> HTTP任务超时时间不能超过300

感谢您的回复,如果有需求要超过300S,需要在哪里进行设置

**Comment by a717445834** [comment]
> HTTP任务超时时间不能超过300
突然想到可以直接命令行使用,谢谢了
