### ISSUE TITLE
[问题] 我没有设置超时时间, 但是却显示超时强制关闭了

### ISSUE THREAD

**Issue by CLannadZSY** [ouqiang/gocron#250]
![image](https://user-images.githubusercontent.com/38000492/88653474-b67ae780-d0fe-11ea-86f1-7cac8a9615b9.png)
![image](https://user-images.githubusercontent.com/38000492/88653504-c09ce600-d0fe-11ea-9649-cb55cf06e6be.png)
![image](https://user-images.githubusercontent.com/38000492/88653546-d01c2f00-d0fe-11ea-9f86-aaeb61670580.png)

日志与设置如图, 请问是为什么?

**Comment by mxcjohn** [comment]
默认一天超时

**Comment by CLannadZSY** [comment]
> 默认一天超时

能否修改这个`默认一天超时`的设置, 我有的任务会运行很长时间
