### ISSUE TITLE
碰到一个调度端信号监听的bug

### ISSUE THREAD

**Issue by zhangya4548** [ouqiang/gocron#253]
问题复现流程:
1. 当前有一个很长的任务在执行中
2.调度端进程 是通过 supervisor 守护, supervisor配置文件中指定的是 stopsignal=TERM
3.这时候重启supervisor的调度端进程, 发现调度端进程会有 10 秒钟等待,所有任务的执行
4.10 秒后由于调度端进程没有对supervisor通知说: 我平滑关闭进程了, 
    这时候supervisor直接主动 kill -9 杀死了调度端进程,导致在执行中的任务没有执行完
5. supervisor重启完成后,进入调度端后台,任务日志中,可以看到没有执行完成的任务,一直是执行中,点强制停止也没用

以上是我发现的问题,然后多次通过上述步骤能重试出此 bug,还望作者考虑下能有什么方式解决掉这个 bug不

**Comment by ouqiang** [comment]
设计如此，收到退出信号如果有正在执行的任务会一直等待直到任务执行完成。
