### ISSUE TITLE
停止执行时间很长的任务，，

### ISSUE THREAD

**Issue by reflyhight** [ouqiang/gocron#26]
###  第一个问题
如果一个任务执行时间比较长，比如一个爬虫程序。启动后，发现无法手动停止本次任务。。
###  第二个问题
java -jar xxx.jar的一个任务，我看执行日志是“执行中”，但本地用jps检查，并没有Java进程存在。

![](http://ou9e0q35h.bkt.clouddn.com/QQ%E6%88%AA%E5%9B%BE20171118185800.png)
![](http://ou9e0q35h.bkt.clouddn.com/QQ%E6%88%AA%E5%9B%BE20171118185709.png)

**Comment by ouqiang** [comment]
1. 不支持停止处于运行中的任务，可以设置任务超时时间，超时会强制kill进程
2. 任务状态为`执行中`表示调度器还没有收到任务节点的响应, 如果任务进程退出会立即返回
    问题排查:
      * 再次确认进程是否有运行 `ps aux | grep java`
      * 查看gocron和gocron-node输出日志
      * 记录任务运行状态, 比如每隔几秒往文件中写入当前时间
