### ISSUE TITLE
任务时长执行时长不能超过24小时的问题

### ISSUE THREAD

**Issue by Jackyqs** [ouqiang/gocron#268]
设置的任务执行时长为默认的0，当执行到24小时任务被强制结束。

**Comment by linian365boy** [comment]
![WX20200916-183457](https://user-images.githubusercontent.com/7359239/93326429-5b868680-f84b-11ea-9d98-486dff50e7dd.png)
有说明的

**Comment by RuofengMao** [comment]
这个问题今天在我们的项目就被排查到了，希望大家以后多多注意
