### ISSUE TITLE
webhook的配置格式

### ISSUE THREAD

**Issue by jiangzhiyun-yun** [ouqiang/gocron#272]
设置Header[ Content-Type: application/json]  这个怎么配置的？下面是默认的模板，但是设置Header[ Content-Type: application/json] 是放在那的？
{
任务ID:{{.TaskId}},
任务名称:{{.TaskName}},
状态:{{.Status}},
执行结果:{{.Result}}
}

**Comment by ouqiang** [comment]
不用配置，请求webhook server时自动设置这个header。
