### ISSUE TITLE
webhook配置钉钉,没有成功

### ISSUE THREAD

**Issue by ahua8** [ouqiang/gocron#277]
url:  https://oapi.dingtalk.com/robot/send?access_token=***
模板:
{
    "msgtype": "text",
    "text": {
        "content": "Task ID:{{.TaskId}}\nTask Name:{{.TaskName}}\nStatus:{{.Status}}\nResult:{{.Result}}"
    }
}

**Comment by czxin788** [comment]
飞书的webhook模板如下：

{
"msg_type": "text",
"content": {
"text": "Task ID:{{.TaskId}}\nTask Name:{{.TaskName}}\nStatus:{{.Status}}\nResult:{{.Result}}"
}
}

**Comment by czxin788** [comment]
邮件的模板
任务ID:  {{.TaskId}}
任务名称: {{.TaskName}}
状态:    {{.Status}}
执行结果: {{.Result}}
