### ISSUE TITLE
延迟API的使用

### ISSUE THREAD

**Issue by shuyabin** [ouqiang/gocron#3]
![image](https://cloud.githubusercontent.com/assets/14884581/26383443/4396754a-4065-11e7-993b-288f7c87cc5a.png)

@ouqiang  大神你好，我在使用延迟API的时候.为什么会获取不到参数.?

**Comment by ouqiang** [comment]
![gocron-issues-3](https://cloud.githubusercontent.com/assets/12163055/26383893/2997ecb6-4068-11e7-94b3-b35bc57097ea.png)
Body类型选择 x-www-form-urlencoded

**Comment by shuyabin** [comment]
谢谢大神, close();
