### ISSUE TITLE
执行任务BUG

### ISSUE THREAD

**Issue by ihaiker** [ouqiang/gocron#30]
问题一：超时
页面提示： `<label>任务超时时间(秒, 0-86400)</label>`
但是添加代码控制如下
```
if taskModel.Timeout > 300 {
	return json.CommonFailure("HTTP任务超时时间不能超过300秒")
}
```
执行代码控制如下：
```
func (h *HTTPHandler) Run(taskModel models.Task) (result string, err error) {
	if taskModel.Timeout <= 0 || taskModel.Timeout > HttpExecTimeout {
		taskModel.Timeout = HttpExecTimeout
	}
```
首先不统一，定时任务肯定是一些长时间运行的离线任务。这个时间对于某些应用来讲太短。

问题二： 
任务执行异常，每次重试间隔时间，每次递增1分钟，会不会这个时间太长。给一个时间递增算法(1 + 2^N)，或者给出一个设置方式最好。

**Comment by ouqiang** [comment]
问题一：这是HTTP请求，执行300秒已经足够长了, SHELL任务没有这样的限制
问题二:  允许用户自定义重试间隔时间，未设置则按默认重试策略执行，这样也许会更好。

**Comment by eltonbfw** [comment]
> 问题一：这是HTTP请求，执行300秒已经足够长了, SHELL任务没有这样的限制
> 问题二: 允许用户自定义重试间隔时间，未设置则按默认重试策略执行，这样也许会更好。

有些接口300秒确实执行不完
