### ISSUE TITLE
API 仍然报 403

### ISSUE THREAD

**Issue by dgben2015** [ouqiang/gocron#32]
版本 gocron-v1.3-windows-amd64.zip

无论配置

`api.sign.enable = false`

H:\X\tool>curl -i -X "POST" 127.0.0.1:5920/api/v1/task/disable/3
HTTP/1.1 403 Forbidden
Set-Cookie: MacaronSession=4fbdcf8be1b5e725; Path=/; HttpOnly
Date: Mon, 25 Dec 2017 14:54:59 GMT
Content-Length: 0
Content-Type: text/plain; charset=utf-8

**Comment by dgben2015** [comment]
代码问题还是 在 上次修改的那一个bug， routers.go
func urlAuth
中，只允许了 `/api` 实际访问URI 是` /api/v1/task/disable/:id `  ，无法匹配到普通用户 url，导致这里出现403.

更换 admin MacaronSession 后问题解决 ，麻烦修复一下，谢谢

**Comment by ouqiang** [comment]
已修复
