### ISSUE TITLE
使用中出现"取消"

### ISSUE THREAD

**Issue by luweiv9988** [ouqiang/gocron#33]
![9a9ee3bc-be6b-48f7-962f-e4b4f49fc149](https://user-images.githubusercontent.com/10349332/34473309-27140fb2-efac-11e7-991d-7a584dbf810e.png)
这个问题怎么处理？

**Comment by luweiv9988** [comment]
重启go_cron web又可以了，是master的调度都基于web 吗？

**Comment by ouqiang** [comment]
增加cron调度间隔时间
[单示例运行] (https://github.com/ouqiang/gocron/wiki/%E5%AE%9A%E6%97%B6%E4%BB%BB%E5%8A%A1#%E5%8D%95%E5%AE%9E%E4%BE%8B%E8%BF%90%E8%A1%8C)
