### ISSUE TITLE
很神奇的一个bug

### ISSUE THREAD

**Issue by wolf-leo** [ouqiang/gocron#330]
本来 一个定时任务里面 有4个节点在跑
最近多加了一个节点 同样的5921 也是可以连通的
但就是因为加了这一个节点后 这个任务不管怎么执行（自动+手动 都无效）
没有日志 也没有执行成功或失败的提示

但是把5个节点单独分开执行又都是可以的。。。
搞不懂

**Comment by baiyongjie** [comment]
因为表中对主机名有长度限制, 改一下就可以跑多个节点了

ALTER TABLE task_log MODIFY hostname text NOT NULL ;

**Comment by wolf-leo** [comment]
> 因为表中对主机名有长度限制, 改一下就可以跑多个节点了
> 
> ALTER TABLE task_log MODIFY hostname text NOT NULL ;

竟然是这个原因！！！
建议可以升级成utf8mb4字符集，长字符串的改用json类型存储，没有去看数据库真的不知道什么原因了。。。
