### ISSUE TITLE
html/template: "install/create" is undefined

### ISSUE THREAD

**Issue by evimagezx** [ouqiang/gocron#35]
自己从代码编译执行时在http://127.0.0.1:5920/install页面显示的，请问这是什问题。win7环境

**Comment by ouqiang** [comment]
templates/install/create.html  模板文件不存在，你有做什么修改吗

**Comment by evimagezx** [comment]
什么修改也没做啊，我用的是jetBrains的goland开发环境，调试的程序在github.com\ouqiang\gocron\cmd\gocron\gocron.exe

**Comment by ouqiang** [comment]
程序运行时根目录必须是templates,conf等所在目录
在github.com\ouqiang\gocron目录下运行gocron.exe

**Comment by evimagezx** [comment]
嗯，可以了。问题就是出在gocron.exe的生成目录路径不对，
