### ISSUE TITLE
请教slack如何配置，最好给一个示例

### ISSUE THREAD

**Issue by evimagezx** [ouqiang/gocron#36]
现在web端和node都可以正常执行任务了，对slack有些陌生，请教slack如何配置，实际意义如何，最好给一个示例

**Comment by ouqiang** [comment]
[Slack Webhook](https://www.google.com/search?safe=strict&source=hp&ei=wmaaWuWVCoP88QW6w6H4AQ&q=slack+web+hook&oq=slack+web+hook&gs_l=psy-ab.3..0i10k1j0i10i30k1j0i8i10i30k1j0i10i30k1j0i5i10i30k1j0i5i30k1.598.3338.0.3575.15.11.0.0.0.0.377.1869.0j1j1j4.6.0....0...1c.1.64.psy-ab..9.6.1867.0..0j0i30k1.0.ZJsVoE0n-mY)
如果不熟悉，就用邮件通知吧
