### ISSUE TITLE
建议增加 sqlite 数据库

### ISSUE THREAD

**Issue by ztj1993** [ouqiang/gocron#37]
建议增加 sqlite 数据库，这样可以进一步提升安装体验，减少运维难度，毕竟有些情况下单机并没有 mysql。

**Comment by ouqiang** [comment]
后期考虑支持sqlite

**Comment by ztj1993** [comment]
期待中

**Comment by painkiller0513** [comment]
建议增加　＋1
代码管理工具 Gogs 支持 SQLite，安装起来很方便，最关键的是运维成本非常非常非常低！
