### ISSUE TITLE
删除定时任务,为什么数据库的数据不会删除?

### ISSUE THREAD

**Issue by shuyabin** [ouqiang/gocron#4]
@ouqiang  大神你好, 删除定时任务,为什么数据不会删除 。。
![image](https://cloud.githubusercontent.com/assets/14884581/26492515/1f1248e6-4247-11e7-988b-d99b0831a4ce.png)

**Comment by ouqiang** [comment]
软删除

**Comment by shuyabin** [comment]
刚找到了. 还以为是BUG .谢谢了
