### ISSUE TITLE
windows版本怎么实现安装成后台服务呢

### ISSUE THREAD

**Issue by zhwjh** [ouqiang/gocron#40]
如题

**Comment by ouqiang** [comment]
[winsw](https://github.com/kohsuke/winsw)

**Comment by zhwjh** [comment]
xml配置文件该怎么设置，我配置后无法启动服务

**Comment by zhwjh** [comment]
@ouqiang xml配置文件该怎么设置，我配置后无法启动服务

**Comment by zhwjh** [comment]
@ouqiang 
![image](https://user-images.githubusercontent.com/22079456/37239085-c62d0462-246f-11e8-92bc-a311bd1d47b6.png)  自己已经尝试成功，帮看下配置是否正确

**Comment by ouqiang** [comment]
我没用过，不知道怎么配置，你可以去官方问问

**Comment by zhwjh** [comment]
@ouqiang 刚刚试了下已经成功启动了，web也可以访问了

**Comment by zhwjh** [comment]
@ouqiang 感谢推荐
