### ISSUE TITLE
邮件通知无法发送

### ISSUE THREAD

**Issue by zhwjh** [ouqiang/gocron#41]
配置均正确，任务执行后就是不能正常发送邮件，请问需要安装说明依赖服务么

**Comment by ouqiang** [comment]
查看日志log/cron.log，是否有记录错误

**Comment by zhwjh** [comment]
@ouqiang [ERR] mail#发送消息失败#unencrypted connection#

**Comment by ouqiang** [comment]
配置的端口是多少

**Comment by zhwjh** [comment]
@ouqiang 2525

**Comment by ouqiang** [comment]
只支持465端口

**Comment by zhwjh** [comment]
@ouqiang ok,明白了，谢谢

**Comment by ccxuy** [comment]
日志报错：x509: certificate is valid for xxx, not xxx
公司stmp服务器证书问题，尝试安装证书无果，能关闭这个检查么？
