### ISSUE TITLE
希望http任务 可以添加解析返回值的模块

### ISSUE THREAD

**Issue by laohubuchiyu** [ouqiang/gocron#43]
现在只能通过http status code来判断吧

**Comment by ouqiang** [comment]
目前是判断状态码等于200则视为成功

**Comment by 17768810** [comment]
是，最好要加上返回值判断，

**Comment by 17768810** [comment]
还有，http post时，要可以支持 params和 content-type的输入

**Comment by 17768810** [comment]
> 现在只能通过http status code来判断吧

我发现，现在有个关键字匹配通知，可以满足返回值判断。。但是有点奇怪，他没有加入http code 非200的情况。。

**Comment by Jinrenjie** [comment]
@laohubuchiyu @17768810 我目前正在实现这方面的功能，可以关注 https://github.com/betterde/ects，希望一起讨论需求
