### ISSUE TITLE
希望能支持python执行

### ISSUE THREAD

**Issue by yelangchs** [ouqiang/gocron#44]
如果能直接执行python就更加完美了

**Comment by yelangchs** [comment]
<img width="831" alt="image" src="https://user-images.githubusercontent.com/3895987/38807256-9d52f586-41ae-11e8-9c76-a33e705f2b4f.png">
 这里导致我不能运行，为啥这个是unknow

**Comment by ouqiang** [comment]
直接执行?

[Unknwon](https://github.com/Unknwon)这是无闻的git仓库名
