### ISSUE TITLE
严重的 BUG：html/template: "install/create" is undefined

### ISSUE THREAD

**Issue by ztj1993** [ouqiang/gocron#45]
当我在根目录执行：/path/gocron/gocron web
提示：html/template: "install/create" is undefined
版本：V1.4

注：/path 是我的程序目录

应该是程序跟路径定义产生的问题，我原本以问是权限问题，结果发现并不是。

**Comment by ouqiang** [comment]
参考 #35

**Comment by ztj1993** [comment]
我也是刚刚看到，但是着应该属于 bug 吧

**Comment by ouqiang** [comment]
目前设计如此

**Comment by ztj1993** [comment]
好吧
