### ISSUE TITLE
建议功能以及现有的解决方案

### ISSUE THREAD

**Issue by ztj1993** [ouqiang/gocron#46]
我有一个业务需求如下：
- 有一个任务，每分钟执行一次，失败重试 2 次
- 任务失败，提示用户 (邮件)，并终止任务运行

现有的功能实现方案：
- 当任务最终失败，调用 URL 通知
- URL接收端调用 API 终止任务，URL接收端提示用户 (发邮件)
- 用户处理过后，API 调用开启任务

现有的功能具体方案：
- PHP 接收 Slack 通知并提取数据
- PHP 根据提取的数据进行分析

建议的功能：
- 建议增加 URL POST 推送任务执行结果
- 建议增加任务执行结果多端推送
- 建议增加任务执行失败后(重试失败后)终止任务

好想学一下 Go 语言呀，现在我有大量的服务器运维软件都是 Go 语言写的。

**Comment by ouqiang** [comment]
建议增加 URL POST 推送任务执行结果
> 增加webhook的通知方式

建议增加任务执行结果多端推送
>  这个可以支持

建议增加任务执行失败后(重试失败后)终止任务
>  还是按目前的方式处理吧，调用API开启或关闭任务。

**Comment by ztj1993** [comment]
如果核心功能与管理功能分离，然后通过 webservices api 通信，强化 api 功能，这样 gocron 就可以与任意系统整合了，对 gocron 壮大也许不错。

**Comment by ouqiang** [comment]
嗯，打算前后端分离

**Comment by ztj1993** [comment]
好的，如果前后端分离，前端有些任务可以让社区来做，Go 语言不太会，前端还是没问题的。
