### ISSUE TITLE
开启端口后  访问 提示    html/template: "install/create" is undefined

### ISSUE THREAD

**Issue by chosen1cwp** [ouqiang/gocron#47]
开启端口后  访问 提示    html/template: "install/create" is undefined

**Comment by ouqiang** [comment]
参考 #35, 这个问题下个版本会解决

**Comment by chosen1cwp** [comment]
我安装时直接make,编译的，有这个问题，
重新编译
`go build -tags gocron -o gocron`
`go build -tags node -o gocron-node`
问题解决

**Comment by ouqiang** [comment]
make编译后，在gocron目录下执行  `./bin/gocron web`
