### ISSUE TITLE
HI,大神你好.

### ISSUE THREAD

**Issue by shuyabin** [ouqiang/gocron#5]
@ouqiang  大神你好, 请问大神有没有开发计划. 一个定时开始时间和结束时间. 可以控制,要不定时任务开始了,就一定要人为的去关闭.

![image](https://cloud.githubusercontent.com/assets/14884581/26771756/b02cb970-49f3-11e7-8c74-8371af636ec0.png)

**Comment by ouqiang** [comment]
下一版本开始支持
