### ISSUE TITLE
 命令输出转换编码失败(gbk to utf8) 

### ISSUE THREAD

**Issue by smirkcat** [ouqiang/gocron#51]
我认为这里处理不太好 我用windows，go编译的二进制输出的应该不是gbk 转换失败 转换失败之后是不是应该保持原样，不然不知道输出的是什么   或者不转

**Comment by ouqiang** [comment]
这跟go没关系，是调用windows命令输出是gbk，所以才需要进行转换，其他平台不需要。
你的系统编码是什么， 我改一下，转换失败保留原始值。

**Comment by smirkcat** [comment]
![default](https://user-images.githubusercontent.com/13444394/39920394-81c47674-5549-11e8-8798-598b2b3f3407.png)

**Comment by ouqiang** [comment]
这是gbk没错啊

**Comment by ouqiang** [comment]
保留原始值也是乱码，没什么用

**Comment by smirkcat** [comment]
在有英文时还是有用的 至少会看到英文部分的 
我是在调用这个https://github.com/henrylee2cn/pholcus  -_ui=cmd以及自己写的go程序出现的编码转化失败 我去掉那个编码转化就是正常的了 
直接调用命令行输出也是正常的

**Comment by ouqiang** [comment]
我加个转换失败保留原始值吧

**Comment by smirkcat** [comment]
ok.
