### ISSUE TITLE
服务节点怎么配置

### ISSUE THREAD

**Issue by bejea** [ouqiang/gocron#52]
gocron-node 开启后，提示无法连接远程服务器。
比如我添加本机 127.0.0.1   端口:5921
看下了5921端口服务也确实运行中

**Comment by ouqiang** [comment]
哪里提示无法连接远程服务器

**Comment by bejea** [comment]
我自己源码编译调试的时候提示的
transport: http2Server.HandleStreams received bogus greeting from client: "GET / HTTP/1.1\r\nHost: 12"
不过我在服务器上直接用你的二进制文件是可以的，这个我回头再看看。

同时问个多节点的问题
我试了下，配置了多节点的任务，执行的时候是多个节点都执行了。我理解的多节点是单点执行，而且某个节点不可用，选取可用节点处理。

**Comment by bejea** [comment]
你现在定义的多节点是同时处理各自的任务吗，如果只是这个作用，意义不大，即使没有多节点配置，简单的多配置几个任务也OK

**Comment by ouqiang** [comment]
多节点执行任务，没有关联
