### ISSUE TITLE
gocron1.5无法编译

### ISSUE THREAD

**Issue by zaite** [ouqiang/gocron#57]
![qq 20180530133027](https://user-images.githubusercontent.com/22079456/40700824-d104e6ec-640d-11e8-9a9c-50a06a69512c.png)

**Comment by ouqiang** [comment]
Go版本是多少

**Comment by zaite** [comment]
@ouqiang 1.8

**Comment by zaite** [comment]
@ouqiang 
![qq 20180530154403](https://user-images.githubusercontent.com/22079456/40706418-5073aca8-6420-11e8-9e5b-ff2629b17ac7.png)

**Comment by ouqiang** [comment]
README.md 写了 Go 1.9+

**Comment by zaite** [comment]
@ouqiang 谢谢

**Comment by YuanDdQiao** [comment]
\internal\routers\task\task.go:153:10: assignment mismatch: 2 variables but 1 values

**Comment by tttlkkkl** [comment]
> \internal\routers\task\task.go:153:10: assignment mismatch: 2 variables but 1 values

我也遇到了这个问题，go 版本 go version go1.11.5 linux/amd64
