### ISSUE TITLE
webhook通知该怎么配置钉钉机器人

### ISSUE THREAD

**Issue by longfengfirst** [ouqiang/gocron#58]
我使用钉钉机器人来实现报警提醒，钉钉机器人有webhook地址，但是设置后，发现接受不到信息，想咨询下是否还需要其它的配置？

**Comment by ouqiang** [comment]
先确认下哪里有问题，是通知发送失败，还是通知内容不符合钉钉规则，所以没显示
看下log/cron.log是否有错误日志输出

**Comment by longfengfirst** [comment]
我不知道怎么排查问题，目前情况是命令能够正常执行，但是webhook通知不知道有没有发送，钉钉没有收到消息。

**Comment by kt10001** [comment]
gocron的默认模板不对，需要修改成钉钉接口的参数，例如
{
     "msgtype": "markdown",
     "markdown": {
         "title":"定时任务管理平台通知",
         "text": "#### 定时任务管理平台通知 \n > task_id: {{.TaskId}} \n\n > task_name: {{.TaskName}} \n\n > status: {{.Status}} \n\n > result: {{.Result}}"
     }
 }

我的webhook是关键字通知，可以按照自己的需求修改

**Comment by DBAAJ** [comment]
腾讯云企业微信机器人换成Content即可：
{
"msgtype": "markdown",
"markdown": {
"title":"定时任务管理平台通知",
"text": "#### 定时任务管理平台通知 \n > task_id: {{.TaskId}} \n\n > task_name: {{.TaskName}} \n\n > status: {{.Status}} \n\n > result: {{.Result}}"
}
}

**Comment by uglyliu** [comment]
Lark机器人模板：

{
    "msg_type": "post",
    "content": {
        "post": {
            "zh_cn": {
                "title": "定时任务管理平台通知",
                "content": [
                    [
                        {
                            "tag": "text",
                            "text": "任务编号: {{.TaskId}}\n任务名称: {{.TaskName}}\n任务状态: {{.Status}}\n执行结果: {{.Result}} "
                        },
                        {
                            "tag": "a",
                            "text": "请查看",
                            "href": "https://gocron.joinbrix.com.cn/"
                        }
                    ]
                ]
            }
        }
    }
}

**Comment by aixj1984** [comment]
`
{
    "msg_type": "post", 
    "content": {
        "post": {
            "zh_cn": {
                "title": "定时任务管理平台通知", 
                "content": [
                    [
                        {
                            "tag": "text", 
                            "text": "任务编号: {{.TaskId}}
任务名称: {{.TaskName}}
任务状态: {{.Status}}
执行结果: {{.Result}} "
                        }, 
                        {
                            "tag": "a", 
                            "text": "请查看", 
                            "href": "https://gocron.joinbrix.com.cn/"
                        }
                    ]
                ]
            }
        }
    }
}
`
