### ISSUE TITLE
一直提示表单验证失败

### ISSUE THREAD

**Issue by code-geeker** [ouqiang/gocron#59]
填写了 数据库信息  没有红色警告   提交表单提示 表单验证失败  求解决

**Comment by ouqiang** [comment]
你提交的信息是什么，浏览器控制台看下接口返回值

**Comment by code-geeker** [comment]
<img width="1342" alt="wx20180615-101803 2x" src="https://user-images.githubusercontent.com/2195007/41447025-ac6a54dc-7085-11e8-86a3-082cf74e5f76.png">

**Comment by code-geeker** [comment]
非常感谢问题已解决
ps. 能显示具体错误信息就很棒了

**Comment by ouqiang** [comment]
嗯，提示信息不够友好。

**Comment by cyandeep** [comment]
大佬，我用了v1.5和v1.5.3都报这个错，（密码也是六位）帮忙看看
