### ISSUE TITLE
windows下读取Root_CA.crt失败

### ISSUE THREAD

**Issue by xiucaiwu** [ouqiang/gocron#68]
failed to read ca cert file: F:/gowork/gocron-windows-amd64/Root_CA.crt

**Comment by xiucaiwu** [comment]
文件是存在的,而且在配置文件中也指定了路径
`app.name          = 定时任务管理系统
api.key           = 
api.secret        = 
enable_tls        = true
concurrency.queue = 500
auth_secret       = d13b0be1dccffe71928e34b0e294dbc72c23bad72370692d8944c206ed2653bf
ca_file           = F:/gowork/gocron-windows-amd64/Root_CA.crt
cert_file         = F:/gowork/gocron-windows-amd64/127.0.0.1.crt
key_file          = F:/gowork/gocron-windows-amd64/127.0.0.1.key`

**Comment by xiucaiwu** [comment]
你在wiki的安全TLS双向认证中出现了笔误
`
Root_CA.key    
127.0.0.1.crt    
127.0.0.1.key
上面3个文件拷贝到gocron服务器    
修改私钥127.0.0.1.key权限，只能被运行gocron的用户读取    
`
是Root_CA.crt而不是Root_CA.key

**Comment by xiucaiwu** [comment]
我的gocron-node节点启动命令为
./gocron-node -enable-tls -ca-file Root_CA.crt -cert-file 10.16.5.20.crt -key-file 10.16.5.20.key
启动成功,
gocron启动的配置文件为
ca_file           = F:/gowork/gocron-windows-amd64/Root_CA.crt
cert_file         = F:/gowork/gocron-windows-amd64/127.0.0.1.crt
key_file          = F:/gowork/gocron-windows-amd64/127.0.0.1.key
可以启动成功,但是输入http://localhost:5920/debug,显示的是认证失败

**Comment by ouqiang** [comment]
http://localhost:5920/debug  现版本已经不支持了

**Comment by xiucaiwu** [comment]
那这个安全 TLS双向认证还有什么意义

**Comment by ouqiang** [comment]
我是说这个debug地址   http://localhost:5920/debug，已经不能访问了。

**Comment by xiucaiwu** [comment]
gocron-node是以lifesonic身份运行的
[lifesonic@127 test]$ ps aux |grep gocron-node
lifeson+ 19777  0.0  0.0  13152  6504 ?        Sl   15:55   0:00 ./gocron-node -enable-tls -ca-file Root_CA.crt -cert-file 10.16.5.20.crt -key-file 10.16.5.20.key
lifeson+ 21313  0.0  0.0 112724   976 pts/2    S+   16:06   0:00 grep --color=auto gocron

php-fpm进程也是以lifesonic身份运行的
[lifesonic@127 test]$ ps aux|grep php-fpm
root     26949  0.0  0.0 152884  7548 ?        Ss   7月03   0:14 php-fpm: master process (/opt/lnmp/php/php-7.2.6/etc/php-fpm.conf)
lifeson+ 26950  0.5  0.1 163420 19740 ?        S    7月03  24:06 php-fpm: pool www
lifeson+ 26951  0.5  0.1 163420 19740 ?        S    7月03  23:57 php-fpm: pool www
lifeson+ 27150  0.5  0.1 163420 19284 ?        S    7月03  21:25 php-fpm: pool www

任务脚本的所有者和群组也是lifesonic
[lifesonic@127 test]$ ll
总用量 24
-rw-r--r-x 1 lifesonic lifesonic 125 6月  29 11:31 a.html
-rw-rw-rwx 1 lifesonic lifesonic  22 7月   6 15:49 a.log
-rw-r--r-- 1 lifesonic lifesonic 343 7月   3 17:57 fcgi.php
-rw-r--r-- 1 lifesonic lifesonic  17 6月  29 11:33 index.php
-rw-rw-r-- 1 lifesonic lifesonic 199 7月   3 17:57 log.txt
-rw-rw-r-- 1 lifesonic lifesonic  59 7月   5 13:49 test.php

如果我直接执行 php test.php是成功执行的,此时我的身份还是lifesonic
但是我在gocron中执行就一直提示我权限错误,这让我很懵逼
任务执行结果
/opt/lnmp/php/php-7.2.6/bin/php /app/lcx_project/test/test.php
主机: [内网服务器-10.16.5.20-10.16.5.20:5921]
PHP Warning:  file_put_contents(a.log): failed to open stream: Permission denied in /app/lcx_project/test/test.php on line 2
