### ISSUE TITLE
版本升级问题

### ISSUE THREAD

**Issue by luweiv9988** [ouqiang/gocron#74]
* 使用1.3版本，升级到1.4版本，数据库表结构好像有变动，如何平滑迁移？
* web端每过几个小时就load会很高，楼主是否有遇见？

**Comment by ouqiang** [comment]
不支持平滑升级  [版本升级](https://github.com/ouqiang/gocron/wiki/%E7%89%88%E6%9C%AC%E5%8D%87%E7%BA%A7)   
负载取决于你跑了多少个定时任务
