### ISSUE TITLE
gocron v1.5  build error 

### ISSUE THREAD

**Issue by cway** [ouqiang/gocron#79]
when i was make the project, the result is 🥇 
go build  -o bin/gocron ./cmd/gocron
cmd/gocron/gocron.go:11:2: use of internal package not allowed
cmd/gocron/gocron.go:12:2: use of internal package not allowed
cmd/gocron/gocron.go:13:2: use of internal package not allowed
cmd/gocron/gocron.go:14:2: use of internal package not allowed
cmd/gocron/gocron.go:15:2: use of internal package not allowed
cmd/gocron/gocron.go:16:2: use of internal package not allowed
make: *** [gocron] Error 1

how to resolve this, please help!
the go version is 1.9.4

**Comment by ouqiang** [comment]
你是怎么安装的

**Comment by cway** [comment]
项目目录 make 安装, 依赖包都通过 go get  xxxxx 来获取了

**Comment by ouqiang** [comment]
完整操作步骤贴一下

**Comment by cway** [comment]
1. unzip v1.5.zip && cd gocron-1.5
2.go get github.com/ouqiang/goutil
   go get github.com/urfave/cli
   go get gopkg.in/macaron.v1
3.make

**Comment by ouqiang** [comment]
```shell
go get github.com/ouqiang/gocron 
cd $GOPATH/github.com/ouqiang/gocron 
make
```

依赖在gocron/vendor中，不需要安装任何依赖

**Comment by blanklin030** [comment]
我是git clone https://github.com/ouqiang/gocron.git的
直接cd gocron后make也报错了
请问需要怎么build？

**Comment by ouqiang** [comment]
需要手动建立包路径
