### ISSUE TITLE
想了解下启动原理

### ISSUE THREAD

**Issue by hakwolf** [ouqiang/gocron#80]
一VUE的文件编译成exe后都打包到exe里了吗？库文件也在里面？exe发布到别的机器上还要另外安装vue的库吗？
二启动时go打开端口5920，这时是如何启动VUE，或者如何到VUE的首页，或者调用到安装页面的，我看BEEGO框架是以go后端打开前端的HTML的，这个VUE一般前后端分离的方式，是要用node.js命令npm run dev启动的 你这个启动不一样，所以我有兴趣了解下。
三这个可否加一个sqlite库的支持，我想如果我发布单独应用的话，就不要求别人装mysql或者别的数据 库了，如果用户用你这个那还要附带装下数据库。

**Comment by hakwolf** [comment]
vue 已经编译打包成普通的js, html了 打包后的文件在哪里？我了解了下nmp run build是可以打包VUE生成普通的js, html，但是你这个好像没有看到编译打包后的js,CSS等文件。另外用goland编译后，这些js是自动编译进exe了吗，以资源形式还是啥形式装进exe的？还请赐教。

**Comment by ouqiang** [comment]
打包后的静态文件写入到Go文件中了
https://github.com/ouqiang/gocron/blob/master/internal/statik/statik.go

**Comment by hakwolf** [comment]
windows下安装这个ＶＵＥ项目的依赖库用的什么命令，打包用的什么命令?

**Comment by ouqiang** [comment]
查看makefile
