### ISSUE TITLE
可以加多个任务开始时的提醒么

### ISSUE THREAD

**Issue by BabyCY** [ouqiang/gocron#83]
如果可以做到多选的话那样更好 在开始时、执行过程中匹配到关键字、以及异常退出或结束时都提醒就好了

**Comment by ouqiang** [comment]
没看懂你的问题

**Comment by BabyCY** [comment]
比如我设置定时执行一个脚本，我需要再这个脚本开始执行的时候发消息通知我该脚本运行了，在脚本运行过程从遇到某些问题，如网络异常等，也通知我去处理，最后再脚本结束的时候，也通知我该脚本已经运行完成了。

**Comment by ouqiang** [comment]
运行过程中出现错误已经结束了，目前已有结束通知。开始通知感觉需求不多，可以在任务开始运行时自行处理。
