### ISSUE TITLE
请问在执行的过程中、手动结束和超时结束后看不到log吗？log是存在哪里的

### ISSUE THREAD

**Issue by BabyCY** [ouqiang/gocron#84]
有些脚本运行过程中出问题了，但是执行的过程中看不到log，手动结束掉也看不到log，只有正常结束才能看到log，这样没办法定位到问题所在。请问有办法解决吗

**Comment by ouqiang** [comment]
日志文件: log/cron.log  

调度器(机器A)和任务节点(机器B)的通信是通过RPC调用，直到任务运行结束才会返回。
手动结束和超时结束都是强制kill进程,  只有进程被kill的日志。

定位问题应该在你的任务脚本中记录运行时间，排查哪里执行耗时
