### ISSUE TITLE
安装初始化一直报 表单验证失败, 请检测输入

### ISSUE THREAD

**Issue by colinrs** [ouqiang/gocron#85]
- 数据库配置
  - 数据库选择
  - MySQL
- 主机名
  - 127.0.0.1
- 端口
  - 3306
- 用户名
  - root
- 密码
  - root
- 数据库名称
  - gocron
- 表前缀
- 管理员账号配置
- 账号
  - admin
- 邮箱
  - admin@qq.com
- 密码
  - root
- 确认密码
 - root

这个输入哪里有错么？

- 日志内容
  - [Macaron] 2018-09-17 23:52:06: Started POST /api/install/store for 127.0.0.1
  - [Macaron] 2018-09-17 23:52:07: Started POST /api/install/store for 127.0.0.1
  - [Macaron] 2018-09-17 23:52:07: Completed /api/install/store 200 OK in 1.9996ms
  - [Macaron] 2018-09-17 23:52:07: Completed /api/install/store 200 OK in 287.0193ms

**Comment by colinrs** [comment]
http://127.0.0.1:5920/#/install  这个页面

**Comment by colinrs** [comment]
.\mysql.exe -h 127.0.0.1 -uroot -proot
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 1
Server version: 5.5.53 MySQL Community Server (GPL)

数据库是可以连接上的

**Comment by ouqiang** [comment]
管理员密码太短，至少6位

**Comment by colinrs** [comment]
> 管理员密码太短，至少6位

现在好了，谢谢～～～

**Comment by colinrs** [comment]
> 遇到了同样问题，看了下源码 数据库密码最大长度30 ｍ（．＿．）ｍ

是的，但是我是因为密码太短了
