### ISSUE TITLE
不支持使用自己搭建的邮件服务器

### ISSUE THREAD

**Issue by gdlwolf** [ouqiang/gocron#88]
不支持使用自己搭建的邮件服务器，
报错：
[ERR] mail#发送消息失败#x509: certificate signed by unknown authority#消息内容

**Comment by ouqiang** [comment]
x509: certificate signed by unknown authority

不支持自签发SSL证书

**Comment by gdlwolf** [comment]
可否修改成可以使用自签发的证书呢？
http://being23.github.io/2015/09/17/%E4%BD%BF%E7%94%A8golang%E5%8F%91%E9%80%81%E9%82%AE%E4%BB%B6/

**Comment by ouqiang** [comment]
你需要把自签发根证书导入系统

**Comment by gdlwolf** [comment]
你好，导入证书还是不行。

我是用的证书是腾讯的免房证书：https://cloud.tencent.com/product/ssl

gocron我安装的是Centos6.8，导入证书的步骤是：
1、我讲腾讯的证书xxx.crt放到了 /etc/pki/ca-trust/source/anchors/目录下。
2、执行命令update-ca-trust和update-ca-trust extract  尝试均无效。

仍然报错：x509: certificate signed by unknown authority

可否指点如何解决？

**Comment by ouqiang** [comment]
导入的是根证书吗，这个需要你自己去排查了。
