### ISSUE TITLE
定时语句解析错误

### ISSUE THREAD

**Issue by Pingze-github** [ouqiang/gocron#91]
\* \*  \*/1实际每秒执行一次。应该是每小时执行一次，不是么？

**Comment by ouqiang** [comment]
？

**Comment by Pingze-github** [comment]
> ？

是定时语句\* \* \*/1，之前显示错了

**Comment by ouqiang** [comment]
* 表示任意
0 0 */1 * * * 
这才是每小时执行一次

**Comment by Pingze-github** [comment]
> 0 0 */1 * * *
> 这才是每小时执行一次

你说得对
