### ISSUE TITLE
保存任务时提示：请求失败 - TypeError: Cannot read property 'code' of null

### ISSUE THREAD

**Issue by flyingPigsIsMe** [ouqiang/gocron#97]
![image](https://user-images.githubusercontent.com/26251366/48113240-f946bd00-e294-11e8-8a28-d99d20ff2bbd.png)

**Comment by ouqiang** [comment]
你提供的信息太少，无法复现

**Comment by flyingPigsIsMe** [comment]
我使用的是最新的release 二进制版本🤔

**Comment by ouqiang** [comment]
使用最新的release二进制版本，按你提供的输入，无法复现。
查看是否有错误日志，看提示是连不上后端。

**Comment by lynch0227** [comment]
估计是没有安装node导致的;需要在任务节点上安装node才可以.

**Comment by yanqibin** [comment]
我也出现这个问题 ，最后通过 按 F12 看下报错。发现时 crontab 命令写错了

**Comment by alexchen1875** [comment]
现在新增任务的时候提示这个错误,看到cron.log中确提示的是编辑任务失败
![image](https://user-images.githubusercontent.com/3668637/55854323-ed8a5a00-5b96-11e9-85bd-279a15d012d2.png)
实际上我是在进行任务的新增操作

**Comment by xiaohuaming** [comment]
我也出现这个问题，最新release版本，请问这是什么原因
![image](https://user-images.githubusercontent.com/22397853/57963085-ce2edb80-7951-11e9-91cf-98433793a0db.png)
![image](https://user-images.githubusercontent.com/22397853/57963088-d8e97080-7951-11e9-831f-5836bdbe64c4.png)

**Comment by ouqiang** [comment]
cron表达式无效

**Comment by xiaohuaming** [comment]
> cron表达式无效

![image](https://user-images.githubusercontent.com/22397853/57963138-bad04000-7952-11e9-9722-c0bb177ecc7f.png)
方便告诉下，哪里写错了吗？谢谢~

**Comment by xiaohuaming** [comment]
> cron表达式无效

可以了。。。好尴尬，谢谢及时回复
