### ISSUE TITLE
支持大于1次的串行依赖吗？

### ISSUE THREAD

**Issue by zongaPanda** [ouqiang/gocron#99]
例如，任务3依赖于任务2，任务二又依赖于任务1。
目前我看只有一层依赖可以实现，但是超过一层的连续依赖好像不可以。

**Comment by ouqiang** [comment]
不支持多级依赖

**Comment by Jinrenjie** [comment]
@zongaPanda 我目前正在实现这方面的功能，可以关注 https://github.com/betterde/ects，
欢迎加入ECTS，群聊号码：872799101，希望一起讨论需求
